# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


class ActionServiceListExecutionsRequest(BaseModel):
    """
    ActionServiceListExecutionsRequest
    """

    pagination: Optional[ActionServicePaginationRequest] = Field(
        default=None, alias="pagination"
    )
    sorting_column: Optional[ActionServiceExecutionFieldName] = Field(
        default=None, alias="sortingColumn"
    )
    filters: Optional[List[ActionServiceExecutionSearchFilter]] = Field(
        default=None, alias="filters", description="Define the criteria to query for."
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.action_service_execution_field_name import (
    ActionServiceExecutionFieldName,
)
from zitadel_client.models.action_service_execution_search_filter import (
    ActionServiceExecutionSearchFilter,
)
from zitadel_client.models.action_service_pagination_request import (
    ActionServicePaginationRequest,
)

ActionServiceListExecutionsRequest.model_rebuild(raise_errors=False)
