# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class ApplicationServiceSAMLConfiguration(BaseModel):
    """
    ApplicationServiceSAMLConfiguration
    """

    metadata_xml: Optional[bytes] = Field(
        default=None,
        alias="metadataXml",
        description="The Metadata XML is the provided or fetched metadata stored at Zitadel.  If either the metadata was provided as XML or when Zitadel fetched it at the provided URL,  it is stored here.",
    )
    metadata_url: Optional[StrictStr] = Field(
        default=None,
        alias="metadataUrl",
        description="The Metadata URL is the URL where the metadata was fetched from.  In case the metadata was provided as raw XML, this field is empty.",
    )
    login_version: Optional[ApplicationServiceLoginVersion] = Field(
        default=None, alias="loginVersion"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr
from zitadel_client.models.application_service_login_version import (
    ApplicationServiceLoginVersion,
)

ApplicationServiceSAMLConfiguration.model_rebuild(raise_errors=False)
