# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class ApplicationServicePaginationRequest(BaseModel):
    """
    ApplicationServicePaginationRequest
    """

    offset: Optional[object] = Field(
        default=None,
        alias="offset",
        description="Starting point for retrieval, in combination of offset used to query a set list of objects.",
    )
    limit: Optional[StrictInt] = Field(
        default=None,
        alias="limit",
        description="limit is the maximum amount of objects returned. The default is set to 100  with a maximum of 1000 in the runtime configuration.  If the limit exceeds the maximum configured ZITADEL will throw an error.  If no limit is present the default is taken.",
    )
    asc: Optional[StrictBool] = Field(
        default=None,
        alias="asc",
        description="Asc is the sorting order. If true the list is sorted ascending, if false  the list is sorted descending. The default is descending.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictBool
from pydantic import StrictInt

ApplicationServicePaginationRequest.model_rebuild(raise_errors=False)
