# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class ApplicationServiceApplicationSearchFilter(BaseModel):
    """
    ApplicationServiceApplicationSearchFilter
    """

    client_id_filter: Optional[ApplicationServiceClientIDFilter] = Field(
        default=None, alias="clientIdFilter"
    )
    entity_id_filter: Optional[ApplicationServiceEntityIDFilter] = Field(
        default=None, alias="entityIdFilter"
    )
    name_filter: Optional[ApplicationServiceApplicationNameFilter] = Field(
        default=None, alias="nameFilter"
    )
    project_id_filter: Optional[ApplicationServiceProjectIDFilter] = Field(
        default=None, alias="projectIdFilter"
    )
    state_filter: Optional[ApplicationServiceApplicationState] = Field(
        default=None, alias="stateFilter"
    )
    type_filter: Optional[ApplicationServiceApplicationType] = Field(
        default=None, alias="typeFilter"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.application_service_application_name_filter import (
    ApplicationServiceApplicationNameFilter,
)
from zitadel_client.models.application_service_application_state import (
    ApplicationServiceApplicationState,
)
from zitadel_client.models.application_service_application_type import (
    ApplicationServiceApplicationType,
)
from zitadel_client.models.application_service_client_id_filter import (
    ApplicationServiceClientIDFilter,
)
from zitadel_client.models.application_service_entity_id_filter import (
    ApplicationServiceEntityIDFilter,
)
from zitadel_client.models.application_service_project_id_filter import (
    ApplicationServiceProjectIDFilter,
)

ApplicationServiceApplicationSearchFilter.model_rebuild(raise_errors=False)
