# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from enum import Enum


class ApplicationServiceOIDCResponseType(str, Enum):
    """
    ApplicationServiceOIDCResponseType
    """

    OIDC_RESPONSE_TYPE_UNSPECIFIED = "OIDC_RESPONSE_TYPE_UNSPECIFIED"
    OIDC_RESPONSE_TYPE_CODE = "OIDC_RESPONSE_TYPE_CODE"
    OIDC_RESPONSE_TYPE_ID_TOKEN = "OIDC_RESPONSE_TYPE_ID_TOKEN"
    OIDC_RESPONSE_TYPE_ID_TOKEN_TOKEN = "OIDC_RESPONSE_TYPE_ID_TOKEN_TOKEN"
