# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from enum import Enum


class BetaUserServiceNotificationType(str, Enum):
    """
    BetaUserServiceNotificationType
    """

    NOTIFICATION_TYPE_UNSPECIFIED = "NOTIFICATION_TYPE_Unspecified"
    NOTIFICATION_TYPE_EMAIL = "NOTIFICATION_TYPE_Email"
    NOTIFICATION_TYPE_SMS = "NOTIFICATION_TYPE_SMS"
