# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class BetaAuthorizationServiceCreateAuthorizationRequest(BaseModel):
    """
    BetaAuthorizationServiceCreateAuthorizationRequest
    """

    user_id: Optional[StrictStr] = Field(
        default=None,
        alias="userId",
        description="UserID is the ID of the user who should be granted the authorization.",
    )
    project_id: Optional[StrictStr] = Field(
        default=None,
        alias="projectId",
        description="Project ID is the ID of the project the user should be authorized for.",
    )
    organization_id: Optional[StrictStr] = Field(
        default=None,
        alias="organizationId",
        description="OrganizationID is the ID of the organization on which the authorization should be created.  The organization must either own the project or have a grant for the project.  If omitted, the authorization is created on the projects organization.",
    )
    role_keys: Optional[List[StrictStr]] = Field(
        default=None,
        alias="roleKeys",
        description="RoleKeys are the keys of the roles the user should be granted.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr

BetaAuthorizationServiceCreateAuthorizationRequest.model_rebuild(raise_errors=False)
