# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class BetaProjectServiceListProjectGrantsRequest(BaseModel):
    """
    BetaProjectServiceListProjectGrantsRequest
    """

    pagination: Optional[BetaProjectServicePaginationRequest] = Field(
        default=None, alias="pagination"
    )
    sorting_column: Optional[BetaProjectServiceProjectGrantFieldName] = Field(
        default=None, alias="sortingColumn"
    )
    filters: Optional[List[BetaProjectServiceProjectGrantSearchFilter]] = Field(
        default=None, alias="filters", description="Define the criteria to query for."
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.beta_project_service_pagination_request import (
    BetaProjectServicePaginationRequest,
)
from zitadel_client.models.beta_project_service_project_grant_field_name import (
    BetaProjectServiceProjectGrantFieldName,
)
from zitadel_client.models.beta_project_service_project_grant_search_filter import (
    BetaProjectServiceProjectGrantSearchFilter,
)

BetaProjectServiceListProjectGrantsRequest.model_rebuild(raise_errors=False)
