# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class BetaUserServiceIDPInformation(BaseModel):
    """
    BetaUserServiceIDPInformation
    """

    idp_id: Optional[StrictStr] = Field(default=None, alias="idpId")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    user_name: Optional[StrictStr] = Field(default=None, alias="userName")
    raw_information: Optional[Dict[str, object]] = Field(
        default=None,
        alias="rawInformation",
        description="`Struct` represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, `Struct`  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for `Struct` is JSON object.",
    )
    ldap: Optional[BetaUserServiceIDPLDAPAccessInformation] = Field(
        default=None, alias="ldap"
    )
    oauth: Optional[BetaUserServiceIDPOAuthAccessInformation] = Field(
        default=None, alias="oauth"
    )
    saml: Optional[BetaUserServiceIDPSAMLAccessInformation] = Field(
        default=None, alias="saml"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr
from zitadel_client.models.beta_user_service_idpldap_access_information import (
    BetaUserServiceIDPLDAPAccessInformation,
)
from zitadel_client.models.beta_user_service_idpo_auth_access_information import (
    BetaUserServiceIDPOAuthAccessInformation,
)
from zitadel_client.models.beta_user_service_idpsaml_access_information import (
    BetaUserServiceIDPSAMLAccessInformation,
)

BetaUserServiceIDPInformation.model_rebuild(raise_errors=False)
