# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class BetaOrganizationServiceDomain(BaseModel):
    """
    from proto/zitadel/org.proto
    """

    organization_id: Optional[StrictStr] = Field(
        default=None, alias="organizationId", description="The Organization id."
    )
    domain_name: Optional[StrictStr] = Field(
        default=None, alias="domainName", description="The domain name."
    )
    is_verified: Optional[StrictBool] = Field(
        default=None,
        alias="isVerified",
        description="Defines if the domain is verified.",
    )
    is_primary: Optional[StrictBool] = Field(
        default=None,
        alias="isPrimary",
        description="Defines if the domain is the primary domain.",
    )
    validation_type: Optional[BetaOrganizationServiceDomainValidationType] = Field(
        default=None, alias="validationType"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictBool
from pydantic import StrictStr
from zitadel_client.models.beta_organization_service_domain_validation_type import (
    BetaOrganizationServiceDomainValidationType,
)

BetaOrganizationServiceDomain.model_rebuild(raise_errors=False)
