# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class BetaUserServiceSearchQuery(BaseModel):
    """
    BetaUserServiceSearchQuery
    """

    and_query: Optional[BetaUserServiceAndQuery] = Field(default=None, alias="andQuery")
    display_name_query: Optional[BetaUserServiceDisplayNameQuery] = Field(
        default=None, alias="displayNameQuery"
    )
    email_query: Optional[BetaUserServiceEmailQuery] = Field(
        default=None, alias="emailQuery"
    )
    first_name_query: Optional[BetaUserServiceFirstNameQuery] = Field(
        default=None, alias="firstNameQuery"
    )
    in_user_emails_query: Optional[BetaUserServiceInUserEmailsQuery] = Field(
        default=None, alias="inUserEmailsQuery"
    )
    in_user_ids_query: Optional[BetaUserServiceInUserIDQuery] = Field(
        default=None, alias="inUserIdsQuery"
    )
    last_name_query: Optional[BetaUserServiceLastNameQuery] = Field(
        default=None, alias="lastNameQuery"
    )
    login_name_query: Optional[BetaUserServiceLoginNameQuery] = Field(
        default=None, alias="loginNameQuery"
    )
    nick_name_query: Optional[BetaUserServiceNickNameQuery] = Field(
        default=None, alias="nickNameQuery"
    )
    not_query: Optional[BetaUserServiceNotQuery] = Field(default=None, alias="notQuery")
    or_query: Optional[BetaUserServiceOrQuery] = Field(default=None, alias="orQuery")
    organization_id_query: Optional[BetaUserServiceOrganizationIdQuery] = Field(
        default=None, alias="organizationIdQuery"
    )
    phone_query: Optional[BetaUserServicePhoneQuery] = Field(
        default=None, alias="phoneQuery"
    )
    state_query: Optional[BetaUserServiceStateQuery] = Field(
        default=None, alias="stateQuery"
    )
    type_query: Optional[BetaUserServiceTypeQuery] = Field(
        default=None, alias="typeQuery"
    )
    user_name_query: Optional[BetaUserServiceUserNameQuery] = Field(
        default=None, alias="userNameQuery"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.beta_user_service_and_query import BetaUserServiceAndQuery
from zitadel_client.models.beta_user_service_display_name_query import (
    BetaUserServiceDisplayNameQuery,
)
from zitadel_client.models.beta_user_service_email_query import (
    BetaUserServiceEmailQuery,
)
from zitadel_client.models.beta_user_service_first_name_query import (
    BetaUserServiceFirstNameQuery,
)
from zitadel_client.models.beta_user_service_in_user_emails_query import (
    BetaUserServiceInUserEmailsQuery,
)
from zitadel_client.models.beta_user_service_in_user_id_query import (
    BetaUserServiceInUserIDQuery,
)
from zitadel_client.models.beta_user_service_last_name_query import (
    BetaUserServiceLastNameQuery,
)
from zitadel_client.models.beta_user_service_login_name_query import (
    BetaUserServiceLoginNameQuery,
)
from zitadel_client.models.beta_user_service_nick_name_query import (
    BetaUserServiceNickNameQuery,
)
from zitadel_client.models.beta_user_service_not_query import BetaUserServiceNotQuery
from zitadel_client.models.beta_user_service_or_query import BetaUserServiceOrQuery
from zitadel_client.models.beta_user_service_organization_id_query import (
    BetaUserServiceOrganizationIdQuery,
)
from zitadel_client.models.beta_user_service_phone_query import (
    BetaUserServicePhoneQuery,
)
from zitadel_client.models.beta_user_service_state_query import (
    BetaUserServiceStateQuery,
)
from zitadel_client.models.beta_user_service_type_query import BetaUserServiceTypeQuery
from zitadel_client.models.beta_user_service_user_name_query import (
    BetaUserServiceUserNameQuery,
)

BetaUserServiceSearchQuery.model_rebuild(raise_errors=False)
