# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from enum import Enum


class BetaAppServiceTextFilterMethod(str, Enum):
    """
    BetaAppServiceTextFilterMethod
    """

    TEXT_FILTER_METHOD_EQUALS = "TEXT_FILTER_METHOD_EQUALS"
    TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE = "TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE"
    TEXT_FILTER_METHOD_STARTS_WITH = "TEXT_FILTER_METHOD_STARTS_WITH"
    TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE = (
        "TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE"
    )
    TEXT_FILTER_METHOD_CONTAINS = "TEXT_FILTER_METHOD_CONTAINS"
    TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE = "TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE"
    TEXT_FILTER_METHOD_ENDS_WITH = "TEXT_FILTER_METHOD_ENDS_WITH"
    TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE = (
        "TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE"
    )
