# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic import StrictStr
from typing import Optional


class BetaSettingsServiceTheme(BaseModel):
    """
    BetaSettingsServiceTheme
    """

    primary_color: Optional[StrictStr] = Field(
        default=None, alias="primaryColor", description="hex value for primary color"
    )
    background_color: Optional[StrictStr] = Field(
        default=None,
        alias="backgroundColor",
        description="hex value for background color",
    )
    warn_color: Optional[StrictStr] = Field(
        default=None, alias="warnColor", description="hex value for warning color"
    )
    font_color: Optional[StrictStr] = Field(
        default=None, alias="fontColor", description="hex value for font color"
    )
    logo_url: Optional[StrictStr] = Field(
        default=None, alias="logoUrl", description="url where the logo is served"
    )
    icon_url: Optional[StrictStr] = Field(
        default=None, alias="iconUrl", description="url where the icon is served"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


BetaSettingsServiceTheme.model_rebuild(raise_errors=False)
