# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BetaInstanceServiceState(str, Enum):
    """
    BetaInstanceServiceState
    """

    """
    allowed enum values
    """
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    STATE_CREATING = 'STATE_CREATING'
    STATE_RUNNING = 'STATE_RUNNING'
    STATE_STOPPING = 'STATE_STOPPING'
    STATE_STOPPED = 'STATE_STOPPED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BetaInstanceServiceState from a JSON string"""
        return cls(json.loads(json_str))


