# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class BetaProjectServiceAddProjectRoleRequest(BaseModel):
    """
    BetaProjectServiceAddProjectRoleRequest
    """

    project_id: Optional[StrictStr] = Field(
        default=None, alias="projectId", description="ID of the project."
    )
    role_key: Optional[StrictStr] = Field(
        default=None,
        alias="roleKey",
        description="The key is the only relevant attribute for ZITADEL regarding the authorization checks.",
    )
    display_name: Optional[StrictStr] = Field(
        default=None, alias="displayName", description="Name displayed for the role."
    )
    group: Optional[StrictStr] = Field(
        default=None,
        alias="group",
        description="The group is only used for display purposes. That you have better handling, like giving all the roles from a group to a user.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr

BetaProjectServiceAddProjectRoleRequest.model_rebuild(raise_errors=False)
