# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic import StrictStr
from typing import Optional


class IdentityProviderServiceJWTConfig(BaseModel):
    """
    IdentityProviderServiceJWTConfig
    """

    jwt_endpoint: Optional[StrictStr] = Field(
        default=None,
        alias="jwtEndpoint",
        description="The endpoint where the JWT can be extracted.",
    )
    issuer: Optional[StrictStr] = Field(
        default=None,
        alias="issuer",
        description="The issuer of the JWT (for validation).",
    )
    keys_endpoint: Optional[StrictStr] = Field(
        default=None,
        alias="keysEndpoint",
        description="The endpoint to the key (JWK) which is used to sign the JWT with.",
    )
    header_name: Optional[StrictStr] = Field(
        default=None,
        alias="headerName",
        description="The name of the header where the JWT is sent in, default is authorization.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


IdentityProviderServiceJWTConfig.model_rebuild(raise_errors=False)
