# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self


class InternalPermissionServiceAdministratorSearchFilter(BaseModel):
    """
    InternalPermissionServiceAdministratorSearchFilter
    """

    and_: Optional[InternalPermissionServiceAndFilter] = Field(
        default=None, alias="and"
    )
    change_date: Optional[InternalPermissionServiceTimestampFilter] = Field(
        default=None, alias="changeDate"
    )
    creation_date: Optional[InternalPermissionServiceTimestampFilter] = Field(
        default=None, alias="creationDate"
    )
    in_user_ids_filter: Optional[InternalPermissionServiceInIDsFilter] = Field(
        default=None, alias="inUserIdsFilter"
    )
    not_: Optional[InternalPermissionServiceNotFilter] = Field(
        default=None, alias="not"
    )
    or_: Optional[InternalPermissionServiceOrFilter] = Field(default=None, alias="or")
    resource: Optional[InternalPermissionServiceResourceFilter] = Field(
        default=None, alias="resource"
    )
    role: Optional[InternalPermissionServiceRoleFilter] = Field(
        default=None, alias="role"
    )
    user_display_name: Optional[InternalPermissionServiceUserDisplayNameFilter] = Field(
        default=None, alias="userDisplayName"
    )
    user_organization_id: Optional[InternalPermissionServiceIDFilter] = Field(
        default=None, alias="userOrganizationId"
    )
    user_preferred_login_name: Optional[
        InternalPermissionServiceUserPreferredLoginNameFilter
    ] = Field(default=None, alias="userPreferredLoginName")

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.internal_permission_service_and_filter import (
    InternalPermissionServiceAndFilter,
)
from zitadel_client.models.internal_permission_service_id_filter import (
    InternalPermissionServiceIDFilter,
)
from zitadel_client.models.internal_permission_service_in_ids_filter import (
    InternalPermissionServiceInIDsFilter,
)
from zitadel_client.models.internal_permission_service_not_filter import (
    InternalPermissionServiceNotFilter,
)
from zitadel_client.models.internal_permission_service_or_filter import (
    InternalPermissionServiceOrFilter,
)
from zitadel_client.models.internal_permission_service_resource_filter import (
    InternalPermissionServiceResourceFilter,
)
from zitadel_client.models.internal_permission_service_role_filter import (
    InternalPermissionServiceRoleFilter,
)
from zitadel_client.models.internal_permission_service_timestamp_filter import (
    InternalPermissionServiceTimestampFilter,
)
from zitadel_client.models.internal_permission_service_user_display_name_filter import (
    InternalPermissionServiceUserDisplayNameFilter,
)
from zitadel_client.models.internal_permission_service_user_preferred_login_name_filter import (
    InternalPermissionServiceUserPreferredLoginNameFilter,
)

InternalPermissionServiceAdministratorSearchFilter.model_rebuild(raise_errors=False)
