# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from zitadel_client.models.beta_project_service_id_filter import BetaProjectServiceIDFilter
from zitadel_client.models.beta_project_service_in_ids_filter import BetaProjectServiceInIDsFilter
from zitadel_client.models.beta_project_service_project_name_filter import BetaProjectServiceProjectNameFilter
from zitadel_client.models.beta_project_service_project_role_display_name_filter import BetaProjectServiceProjectRoleDisplayNameFilter
from zitadel_client.models.beta_project_service_project_role_key_filter import BetaProjectServiceProjectRoleKeyFilter
from typing import Optional, Set
from typing_extensions import Self

class NoOp200Response3(BaseModel):
    """
    NoOp200Response3
    """ # noqa: E501
    var_50e4a42b_a3da_470e_9fa1_2371604e532d: Optional[BetaProjectServiceIDFilter] = Field(default=None, alias="50e4a42b-a3da-470e-9fa1-2371604e532d")
    var_0fcd67bd_c03c_49d4_9152_9fc4b117e9d4: Optional[BetaProjectServiceInIDsFilter] = Field(default=None, alias="0fcd67bd-c03c-49d4-9152-9fc4b117e9d4")
    d7029886_4434_475d_84e7_b132c0a93b64: Optional[BetaProjectServiceProjectNameFilter] = Field(default=None, alias="d7029886-4434-475d-84e7-b132c0a93b64")
    c8ea809e_4f6d_4931_a11a_3d5e56d33650: Optional[BetaProjectServiceProjectRoleDisplayNameFilter] = Field(default=None, alias="c8ea809e-4f6d-4931-a11a-3d5e56d33650")
    c2871028_afd7_4282_b46b_8a9aeecd72b8: Optional[BetaProjectServiceProjectRoleKeyFilter] = Field(default=None, alias="c2871028-afd7-4282-b46b-8a9aeecd72b8")
    __properties: ClassVar[List[str]] = ["50e4a42b-a3da-470e-9fa1-2371604e532d", "0fcd67bd-c03c-49d4-9152-9fc4b117e9d4", "d7029886-4434-475d-84e7-b132c0a93b64", "c8ea809e-4f6d-4931-a11a-3d5e56d33650", "c2871028-afd7-4282-b46b-8a9aeecd72b8"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NoOp200Response3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_50e4a42b_a3da_470e_9fa1_2371604e532d
        if self.var_50e4a42b_a3da_470e_9fa1_2371604e532d:
            _dict['50e4a42b-a3da-470e-9fa1-2371604e532d'] = self.var_50e4a42b_a3da_470e_9fa1_2371604e532d.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_0fcd67bd_c03c_49d4_9152_9fc4b117e9d4
        if self.var_0fcd67bd_c03c_49d4_9152_9fc4b117e9d4:
            _dict['0fcd67bd-c03c-49d4-9152-9fc4b117e9d4'] = self.var_0fcd67bd_c03c_49d4_9152_9fc4b117e9d4.to_dict()
        # override the default output from pydantic by calling `to_dict()` of d7029886_4434_475d_84e7_b132c0a93b64
        if self.d7029886_4434_475d_84e7_b132c0a93b64:
            _dict['d7029886-4434-475d-84e7-b132c0a93b64'] = self.d7029886_4434_475d_84e7_b132c0a93b64.to_dict()
        # override the default output from pydantic by calling `to_dict()` of c8ea809e_4f6d_4931_a11a_3d5e56d33650
        if self.c8ea809e_4f6d_4931_a11a_3d5e56d33650:
            _dict['c8ea809e-4f6d-4931-a11a-3d5e56d33650'] = self.c8ea809e_4f6d_4931_a11a_3d5e56d33650.to_dict()
        # override the default output from pydantic by calling `to_dict()` of c2871028_afd7_4282_b46b_8a9aeecd72b8
        if self.c2871028_afd7_4282_b46b_8a9aeecd72b8:
            _dict['c2871028-afd7-4282-b46b-8a9aeecd72b8'] = self.c2871028_afd7_4282_b46b_8a9aeecd72b8.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NoOp200Response3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "50e4a42b-a3da-470e-9fa1-2371604e532d": BetaProjectServiceIDFilter.from_dict(obj["50e4a42b-a3da-470e-9fa1-2371604e532d"]) if obj.get("50e4a42b-a3da-470e-9fa1-2371604e532d") is not None else None,
            "0fcd67bd-c03c-49d4-9152-9fc4b117e9d4": BetaProjectServiceInIDsFilter.from_dict(obj["0fcd67bd-c03c-49d4-9152-9fc4b117e9d4"]) if obj.get("0fcd67bd-c03c-49d4-9152-9fc4b117e9d4") is not None else None,
            "d7029886-4434-475d-84e7-b132c0a93b64": BetaProjectServiceProjectNameFilter.from_dict(obj["d7029886-4434-475d-84e7-b132c0a93b64"]) if obj.get("d7029886-4434-475d-84e7-b132c0a93b64") is not None else None,
            "c8ea809e-4f6d-4931-a11a-3d5e56d33650": BetaProjectServiceProjectRoleDisplayNameFilter.from_dict(obj["c8ea809e-4f6d-4931-a11a-3d5e56d33650"]) if obj.get("c8ea809e-4f6d-4931-a11a-3d5e56d33650") is not None else None,
            "c2871028-afd7-4282-b46b-8a9aeecd72b8": BetaProjectServiceProjectRoleKeyFilter.from_dict(obj["c2871028-afd7-4282-b46b-8a9aeecd72b8"]) if obj.get("c2871028-afd7-4282-b46b-8a9aeecd72b8") is not None else None
        })
        return _obj


