# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from zitadel_client.models.organization_service_hashed_password import OrganizationServiceHashedPassword
from zitadel_client.models.organization_service_idp_link import OrganizationServiceIDPLink
from zitadel_client.models.organization_service_password import OrganizationServicePassword
from zitadel_client.models.organization_service_set_human_email import OrganizationServiceSetHumanEmail
from zitadel_client.models.organization_service_set_human_phone import OrganizationServiceSetHumanPhone
from zitadel_client.models.organization_service_set_human_profile import OrganizationServiceSetHumanProfile
from zitadel_client.models.organization_service_set_metadata_entry import OrganizationServiceSetMetadataEntry
from zitadel_client.models.zitadelobjectv2_organization import Zitadelobjectv2Organization
from typing import Optional, Set
from typing_extensions import Self

class OrganizationServiceAddHumanUserRequest(BaseModel):
    """
    OrganizationServiceAddHumanUserRequest
    """ # noqa: E501
    user_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = Field(default=None, description="optionally set your own id unique for the user.", alias="userId")
    username: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = Field(default=None, description="optionally set a unique username, if none is provided the email will be used.")
    organization: Optional[Zitadelobjectv2Organization] = None
    profile: OrganizationServiceSetHumanProfile
    email: OrganizationServiceSetHumanEmail
    phone: Optional[OrganizationServiceSetHumanPhone] = None
    metadata: Optional[List[OrganizationServiceSetMetadataEntry]] = None
    password: Optional[OrganizationServicePassword] = None
    hashed_password: Optional[OrganizationServiceHashedPassword] = Field(default=None, alias="hashedPassword")
    idp_links: Optional[List[OrganizationServiceIDPLink]] = Field(default=None, alias="idpLinks")
    totp_secret: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = Field(default=None, description="An Implementation of RFC 6238 is used, with HMAC-SHA-1 and time-step of 30 seconds. Currently no other options are supported, and if anything different is used the validation will fail.", alias="totpSecret")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = []

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationServiceAddHumanUserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationServiceAddHumanUserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


