# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class ProjectServiceListProjectRolesRequest(BaseModel):
    """
    ProjectServiceListProjectRolesRequest
    """

    project_id: Optional[StrictStr] = Field(
        default=None,
        alias="projectId",
        description="ProjectID is the unique identifier of the project.",
    )
    pagination: Optional[ProjectServicePaginationRequest] = Field(
        default=None, alias="pagination"
    )
    sorting_column: Optional[ProjectServiceProjectRoleFieldName] = Field(
        default=None, alias="sortingColumn"
    )
    filters: Optional[List[ProjectServiceProjectRoleSearchFilter]] = Field(
        default=None,
        alias="filters",
        description="Filters define the criteria to query for.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr
from zitadel_client.models.project_service_pagination_request import (
    ProjectServicePaginationRequest,
)
from zitadel_client.models.project_service_project_role_field_name import (
    ProjectServiceProjectRoleFieldName,
)
from zitadel_client.models.project_service_project_role_search_filter import (
    ProjectServiceProjectRoleSearchFilter,
)

ProjectServiceListProjectRolesRequest.model_rebuild(raise_errors=False)
