# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, Optional
from zitadel_client.models.project_service_private_labeling_setting import ProjectServicePrivateLabelingSetting
from typing import Optional, Set
from typing_extensions import Self

class ProjectServiceCreateProjectRequest(BaseModel):
    """
    ProjectServiceCreateProjectRequest
    """ # noqa: E501
    organization_id: Optional[StrictStr] = Field(default=None, description="OrganizationID is the unique identifier of the organization the project belongs to.", alias="organizationId")
    project_id: Optional[StrictStr] = Field(default=None, description="ProjectID is the unique identifier of the new project. This field is optional.  If omitted, the system will generate a unique ID for you. This is the  recommended way. The generated ID will be returned in the response.", alias="projectId")
    name: Optional[StrictStr] = Field(default=None, description="Name of the project. This might be presented to users, e.g. in sign-in flows.")
    project_role_assertion: Optional[StrictBool] = Field(default=None, description="ProjectRoleAssertion is a  setting that can be enabled to have role information  included in the user info endpoint.  It is also dependent on your application settings to include it in tokens and other types.", alias="projectRoleAssertion")
    authorization_required: Optional[StrictBool] = Field(default=None, description="AuthorizationRequired is a boolean flag that can be enabled to check if a user has  an authorization to use this project assigned when login into an application of this project.", alias="authorizationRequired")
    project_access_required: Optional[StrictBool] = Field(default=None, description="ProjectAccessRequired is a boolean flag that can be enabled to check if the organization  of the user, that is trying to log in,  has access to this project (either owns the project or is granted).", alias="projectAccessRequired")
    private_labeling_setting: Optional[ProjectServicePrivateLabelingSetting] = Field(default=None, alias="privateLabelingSetting")
    __properties: ClassVar[List[str]] = ["organizationId", "projectId", "name", "projectRoleAssertion", "authorizationRequired", "projectAccessRequired", "privateLabelingSetting"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectServiceCreateProjectRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['projectId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectServiceCreateProjectRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organizationId": obj.get("organizationId"),
            "projectId": obj.get("projectId"),
            "name": obj.get("name"),
            "projectRoleAssertion": obj.get("projectRoleAssertion"),
            "authorizationRequired": obj.get("authorizationRequired"),
            "projectAccessRequired": obj.get("projectAccessRequired"),
            "privateLabelingSetting": obj.get("privateLabelingSetting")
        })
        return _obj


