# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from enum import Enum


class ProjectServiceProjectFieldName(str, Enum):
    """
    ProjectServiceProjectFieldName
    """

    PROJECT_FIELD_NAME_UNSPECIFIED = "PROJECT_FIELD_NAME_UNSPECIFIED"
    PROJECT_FIELD_NAME_ID = "PROJECT_FIELD_NAME_ID"
    PROJECT_FIELD_NAME_CREATION_DATE = "PROJECT_FIELD_NAME_CREATION_DATE"
    PROJECT_FIELD_NAME_CHANGE_DATE = "PROJECT_FIELD_NAME_CHANGE_DATE"
    PROJECT_FIELD_NAME_NAME = "PROJECT_FIELD_NAME_NAME"
