# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class ProjectServiceUpdateProjectRequest(BaseModel):
    """
    ProjectServiceUpdateProjectRequest
    """

    project_id: Optional[StrictStr] = Field(
        default=None,
        alias="projectId",
        description="ProjectID is the unique identifier of the project to be updated.",
    )
    name: Optional[StrictStr] = Field(
        default=None,
        alias="name",
        description="Name is used to update the name of the project. This field is optional.  If omitted, the name will remain unchanged.",
    )
    project_role_assertion: Optional[StrictBool] = Field(
        default=None,
        alias="projectRoleAssertion",
        description="ProjectRoleAssertion is a setting that can be enabled to have role information  included in the user info endpoint.  It is also dependent on your application settings to include it in tokens and other types.  If omitted, the setting will remain unchanged.",
    )
    authorization_required: Optional[StrictBool] = Field(
        default=None,
        alias="authorizationRequired",
        description="AuthorizationRequired is a boolean flag that can be enabled to check if a user has  a role of this project assigned when logging into an application of this project.  If omitted, the setting will remain unchanged.",
    )
    project_access_required: Optional[StrictBool] = Field(
        default=None,
        alias="projectAccessRequired",
        description="ProjectAccessRequired is a boolean flag that can be enabled to check if the organization  of the user has a grant to this project.  If omitted, the setting will remain unchanged.",
    )
    private_labeling_setting: Optional[ProjectServicePrivateLabelingSetting] = Field(
        default=None, alias="privateLabelingSetting"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictBool
from pydantic import StrictStr
from zitadel_client.models.project_service_private_labeling_setting import (
    ProjectServicePrivateLabelingSetting,
)

ProjectServiceUpdateProjectRequest.model_rebuild(raise_errors=False)
