# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic import StrictStr
from typing import Optional


class SAMLServiceCreateResponseResponse(BaseModel):
    """
    SAMLServiceCreateResponseResponse
    """

    details: Optional[SAMLServiceDetails] = Field(default=None, alias="details")
    url: Optional[StrictStr] = Field(
        default=None,
        alias="url",
        description="URL including the Assertion Consumer Service where the user should be redirected or has to call per POST, depending on the binding. Contains details for the application to obtain the response on success, or error details on failure. Note that this field must be treated as credentials, as the contained SAMLResponse or code can be used on behalve of the user.",
    )
    post: Optional[SAMLServicePostResponse] = Field(default=None, alias="post")
    redirect: Optional[object] = Field(default=None, alias="redirect")

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.saml_service_details import SAMLServiceDetails
from zitadel_client.models.saml_service_post_response import SAMLServicePostResponse

SAMLServiceCreateResponseResponse.model_rebuild(raise_errors=False)
