# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional


class SessionServiceRequestChallenges(BaseModel):
    """
    SessionServiceRequestChallenges
    """

    web_auth_n: Optional[SessionServiceWebAuthN] = Field(default=None, alias="webAuthN")
    otp_sms: Optional[SessionServiceOTPSMS] = Field(default=None, alias="otpSms")
    otp_email: Optional[SessionServiceOTPEmail] = Field(default=None, alias="otpEmail")

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.session_service_otp_email import SessionServiceOTPEmail
from zitadel_client.models.session_service_otpsms import SessionServiceOTPSMS
from zitadel_client.models.session_service_web_auth_n import SessionServiceWebAuthN

SessionServiceRequestChallenges.model_rebuild(raise_errors=False)
