# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic import StrictStr
from typing import Optional


class SessionServiceCreatorQuery(BaseModel):
    """
    SessionServiceCreatorQuery
    """

    id: Optional[StrictStr] = Field(
        default=None,
        alias="id",
        description="ID of the user who created the session. If empty, the calling user's ID is used.",
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


SessionServiceCreatorQuery.model_rebuild(raise_errors=False)
