# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class SessionServiceWebAuthN(BaseModel):
    """
    SessionServiceWebAuthN
    """

    domain: Optional[StrictStr] = Field(
        default=None,
        alias="domain",
        description='The domain on which the session was created. Will be used in the WebAuthN challenge.  It must be either the exact domain or a top-level domain of the origin of the request.  For example if the request is coming from "login.example.com", the domain can be  "login.example.com" or "example.com", but not "other.com" or "sub.login.example.com".  See also: https://www.w3.org/TR/webauthn/#relying-party-identifier',
    )
    user_verification_requirement: Optional[
        SessionServiceUserVerificationRequirement
    ] = Field(default=None, alias="userVerificationRequirement")

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictStr
from zitadel_client.models.session_service_user_verification_requirement import (
    SessionServiceUserVerificationRequirement,
)

SessionServiceWebAuthN.model_rebuild(raise_errors=False)
