# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

import re
import warnings
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Set, Union
from typing_extensions import Self
from enum import Enum


class SettingsServicePasswordComplexitySettings(BaseModel):
    """
    SettingsServicePasswordComplexitySettings
    """

    min_length: Optional[object] = Field(
        default=None,
        alias="minLength",
        description="The minimum length a password must have.",
    )
    requires_uppercase: Optional[StrictBool] = Field(
        default=None,
        alias="requiresUppercase",
        description="Defines if the password MUST contain an upper case letter.",
    )
    requires_lowercase: Optional[StrictBool] = Field(
        default=None,
        alias="requiresLowercase",
        description="Defines if the password MUST contain a lowercase letter.",
    )
    requires_number: Optional[StrictBool] = Field(
        default=None,
        alias="requiresNumber",
        description="Defines if the password MUST contain a number.",
    )
    requires_symbol: Optional[StrictBool] = Field(
        default=None,
        alias="requiresSymbol",
        description='Defines if the password MUST contain a symbol or special character. E.g. "$"',
    )
    resource_owner_type: Optional[SettingsServiceResourceOwnerType] = Field(
        default=None, alias="resourceOwnerType"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from pydantic import StrictBool
from zitadel_client.models.settings_service_resource_owner_type import (
    SettingsServiceResourceOwnerType,
)

SettingsServicePasswordComplexitySettings.model_rebuild(raise_errors=False)
