# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional


class SettingsServicePasswordExpirySettings(BaseModel):
    """
    SettingsServicePasswordExpirySettings
    """

    max_age_days: Optional[object] = Field(
        default=None,
        alias="maxAgeDays",
        description="Amount of days after which a password will expire. The user will be forced to change the password on the following authentication.",
    )
    expire_warn_days: Optional[object] = Field(
        default=None,
        alias="expireWarnDays",
        description="Amount of days after which the user should be notified of the upcoming expiry. ZITADEL will not notify the user.",
    )
    resource_owner_type: Optional[SettingsServiceResourceOwnerType] = Field(
        default=None, alias="resourceOwnerType"
    )

    # Strict primitives (Item 8 — StrictInt/StrictStr/...) carry the
    # per-field strictness, so the model-wide ConfigDict no longer needs
    # strict=True. populate_by_name keeps both alias and snake_case
    # field-name kwargs working in constructors.
    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


from zitadel_client.models.settings_service_resource_owner_type import (
    SettingsServiceResourceOwnerType,
)

SettingsServicePasswordExpirySettings.model_rebuild(raise_errors=False)
