# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from zitadel_client.models.created_date_filter import CreatedDateFilter
from zitadel_client.models.expiration_date_filter import ExpirationDateFilter
from zitadel_client.models.organization_id_filter import OrganizationIdFilter
from zitadel_client.models.token_id_filter import TokenIdFilter
from zitadel_client.models.user_id_filter import UserIdFilter
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

none_type = type(None)
USERSERVICEPERSONALACCESSTOKENSSEARCHFILTER_ONE_OF_SCHEMAS = ["CreatedDateFilter", "ExpirationDateFilter", "OrganizationIdFilter", "TokenIdFilter", "UserIdFilter"]

class UserServicePersonalAccessTokensSearchFilter(BaseModel):
    """
    UserServicePersonalAccessTokensSearchFilter
    """
    # data type: CreatedDateFilter
    oneof_schema_1_validator: Optional[CreatedDateFilter] = None
    # data type: ExpirationDateFilter
    oneof_schema_2_validator: Optional[ExpirationDateFilter] = None
    # data type: OrganizationIdFilter
    oneof_schema_3_validator: Optional[OrganizationIdFilter] = None
    # data type: TokenIdFilter
    oneof_schema_4_validator: Optional[TokenIdFilter] = None
    # data type: UserIdFilter
    oneof_schema_5_validator: Optional[UserIdFilter] = None
    actual_instance: Optional[Union[CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter]] = None
    one_of_schemas: Set[str] = { "CreatedDateFilter", "ExpirationDateFilter", "OrganizationIdFilter", "TokenIdFilter", "UserIdFilter" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = UserServicePersonalAccessTokensSearchFilter.model_construct()
        error_messages = []
        match = 0
        # validate data type: CreatedDateFilter
        if not isinstance(v, CreatedDateFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreatedDateFilter`")
        else:
            match += 1
        # validate data type: ExpirationDateFilter
        if not isinstance(v, ExpirationDateFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExpirationDateFilter`")
        else:
            match += 1
        # validate data type: OrganizationIdFilter
        if not isinstance(v, OrganizationIdFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrganizationIdFilter`")
        else:
            match += 1
        # validate data type: TokenIdFilter
        if not isinstance(v, TokenIdFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TokenIdFilter`")
        else:
            match += 1
        # validate data type: UserIdFilter
        if not isinstance(v, UserIdFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserIdFilter`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in UserServicePersonalAccessTokensSearchFilter with oneOf schemas: CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in UserServicePersonalAccessTokensSearchFilter with oneOf schemas: CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CreatedDateFilter
        try:
            instance.actual_instance = CreatedDateFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ExpirationDateFilter
        try:
            instance.actual_instance = ExpirationDateFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OrganizationIdFilter
        try:
            instance.actual_instance = OrganizationIdFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TokenIdFilter
        try:
            instance.actual_instance = TokenIdFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UserIdFilter
        try:
            instance.actual_instance = UserIdFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into UserServicePersonalAccessTokensSearchFilter with oneOf schemas: CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UserServicePersonalAccessTokensSearchFilter with oneOf schemas: CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CreatedDateFilter, ExpirationDateFilter, OrganizationIdFilter, TokenIdFilter, UserIdFilter]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


