# coding: utf-8

"""
    Zitadel SDK

    The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from zitadel_client.models.v2_check_idp_intent import V2CheckIDPIntent
from zitadel_client.models.v2_check_otp import V2CheckOTP
from zitadel_client.models.v2_check_password import V2CheckPassword
from zitadel_client.models.v2_check_totp import V2CheckTOTP
from zitadel_client.models.v2_check_user import V2CheckUser
from zitadel_client.models.v2_check_web_auth_n import V2CheckWebAuthN


class V2Checks(BaseModel):
    """
    V2Checks
    """ # noqa: E501
    user: Optional[V2CheckUser] = None
    password: Optional[V2CheckPassword] = None
    web_auth_n: Optional[V2CheckWebAuthN] = Field(default=None, alias="webAuthN")
    idp_intent: Optional[V2CheckIDPIntent] = Field(default=None, alias="idpIntent")
    totp: Optional[V2CheckTOTP] = None
    otp_sms: Optional[V2CheckOTP] = Field(default=None, alias="otpSms")
    otp_email: Optional[V2CheckOTP] = Field(default=None, alias="otpEmail")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["user", "password", "webAuthN", "idpIntent", "totp", "otpSms", "otpEmail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V2Checks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict["user"] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of password
        if self.password:
            _dict["password"] = self.password.to_dict()
        # override the default output from pydantic by calling `to_dict()` of web_auth_n
        if self.web_auth_n:
            _dict["webAuthN"] = self.web_auth_n.to_dict()
        # override the default output from pydantic by calling `to_dict()` of idp_intent
        if self.idp_intent:
            _dict["idpIntent"] = self.idp_intent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of totp
        if self.totp:
            _dict["totp"] = self.totp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of otp_sms
        if self.otp_sms:
            _dict["otpSms"] = self.otp_sms.to_dict()
        # override the default output from pydantic by calling `to_dict()` of otp_email
        if self.otp_email:
            _dict["otpEmail"] = self.otp_email.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V2Checks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user": V2CheckUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "password": V2CheckPassword.from_dict(obj["password"]) if obj.get("password") is not None else None,
            "webAuthN": V2CheckWebAuthN.from_dict(obj["webAuthN"]) if obj.get("webAuthN") is not None else None,
            "idpIntent": V2CheckIDPIntent.from_dict(obj["idpIntent"]) if obj.get("idpIntent") is not None else None,
            "totp": V2CheckTOTP.from_dict(obj["totp"]) if obj.get("totp") is not None else None,
            "otpSms": V2CheckOTP.from_dict(obj["otpSms"]) if obj.get("otpSms") is not None else None,
            "otpEmail": V2CheckOTP.from_dict(obj["otpEmail"]) if obj.get("otpEmail") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


