# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V2UserFieldName(str, Enum):
    """
    V2UserFieldName
    """

    """
    allowed enum values
    """
    USER_FIELD_NAME_UNSPECIFIED = 'USER_FIELD_NAME_UNSPECIFIED'
    USER_FIELD_NAME_USER_NAME = 'USER_FIELD_NAME_USER_NAME'
    USER_FIELD_NAME_FIRST_NAME = 'USER_FIELD_NAME_FIRST_NAME'
    USER_FIELD_NAME_LAST_NAME = 'USER_FIELD_NAME_LAST_NAME'
    USER_FIELD_NAME_NICK_NAME = 'USER_FIELD_NAME_NICK_NAME'
    USER_FIELD_NAME_DISPLAY_NAME = 'USER_FIELD_NAME_DISPLAY_NAME'
    USER_FIELD_NAME_EMAIL = 'USER_FIELD_NAME_EMAIL'
    USER_FIELD_NAME_STATE = 'USER_FIELD_NAME_STATE'
    USER_FIELD_NAME_TYPE = 'USER_FIELD_NAME_TYPE'
    USER_FIELD_NAME_CREATION_DATE = 'USER_FIELD_NAME_CREATION_DATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V2UserFieldName from a JSON string"""
        return cls(json.loads(json_str))


