# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from abc import abstractmethod
from typing import Dict

from .authenticator import Authenticator


class BaseAuthenticator(Authenticator):
    """Abstract base class providing default implementations for optional
    Authenticator methods. Concrete authenticators should extend this class.
    """

    @abstractmethod
    def get_host(self) -> str:
        """Returns the base URL of the API."""

    @abstractmethod
    def get_auth_headers(self) -> Dict[str, str]:
        """Returns the authentication headers to include in every request."""

    def get_query_params(self) -> Dict[str, str]:
        """Returns query parameters to include for authentication."""
        return {}

    def get_cookie_params(self) -> Dict[str, str]:
        """Returns cookie parameters to include for authentication."""
        return {}
