# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_user_state import V2UserState

class TestV2UserState(unittest.TestCase):
    """V2UserState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2UserState(self):
        """Test V2UserState"""
        # inst = V2UserState()

if __name__ == '__main__':
    unittest.main()
