# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.user_service_list_idp_links_body import UserServiceListIDPLinksBody

class TestUserServiceListIDPLinksBody(unittest.TestCase):
    """UserServiceListIDPLinksBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserServiceListIDPLinksBody:
        """Test UserServiceListIDPLinksBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserServiceListIDPLinksBody`
        """
        model = UserServiceListIDPLinksBody()
        if include_optional:
            return UserServiceListIDPLinksBody(
                query = zitadel_client.models.general_list_query.General List Query(
                    offset = '0', 
                    limit = 100, 
                    asc = True, )
            )
        else:
            return UserServiceListIDPLinksBody(
        )
        """

    def testUserServiceListIDPLinksBody(self):
        """Test UserServiceListIDPLinksBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
