# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.user_service_register_u2_f_body import UserServiceRegisterU2FBody

class TestUserServiceRegisterU2FBody(unittest.TestCase):
    """UserServiceRegisterU2FBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserServiceRegisterU2FBody:
        """Test UserServiceRegisterU2FBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserServiceRegisterU2FBody`
        """
        model = UserServiceRegisterU2FBody()
        if include_optional:
            return UserServiceRegisterU2FBody(
                domain = ''
            )
        else:
            return UserServiceRegisterU2FBody(
        )
        """

    def testUserServiceRegisterU2FBody(self):
        """Test UserServiceRegisterU2FBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
