# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.zitadelidpv2_options import Zitadelidpv2Options

class TestZitadelidpv2Options(unittest.TestCase):
    """Zitadelidpv2Options unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Zitadelidpv2Options:
        """Test Zitadelidpv2Options
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Zitadelidpv2Options`
        """
        model = Zitadelidpv2Options()
        if include_optional:
            return Zitadelidpv2Options(
                is_linking_allowed = True,
                is_creation_allowed = True,
                is_auto_creation = True,
                is_auto_update = True,
                auto_linking = 'AUTO_LINKING_OPTION_UNSPECIFIED'
            )
        else:
            return Zitadelidpv2Options(
        )
        """

    def testZitadelidpv2Options(self):
        """Test Zitadelidpv2Options"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
