# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_check_totp import V2CheckTOTP

class TestV2CheckTOTP(unittest.TestCase):
    """V2CheckTOTP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2CheckTOTP:
        """Test V2CheckTOTP
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2CheckTOTP`
        """
        model = V2CheckTOTP()
        if include_optional:
            return V2CheckTOTP(
                code = '323764'
            )
        else:
            return V2CheckTOTP(
        )
        """

    def testV2CheckTOTP(self):
        """Test V2CheckTOTP"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
