# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.objectv2_list_query import Objectv2ListQuery

class TestObjectv2ListQuery(unittest.TestCase):
    """Objectv2ListQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Objectv2ListQuery:
        """Test Objectv2ListQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Objectv2ListQuery`
        """
        model = Objectv2ListQuery()
        if include_optional:
            return Objectv2ListQuery(
                offset = '0',
                limit = 100,
                asc = True
            )
        else:
            return Objectv2ListQuery(
        )
        """

    def testObjectv2ListQuery(self):
        """Test Objectv2ListQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
