# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_auth_factor_u2_f import V2AuthFactorU2F

class TestV2AuthFactorU2F(unittest.TestCase):
    """V2AuthFactorU2F unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AuthFactorU2F:
        """Test V2AuthFactorU2F
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AuthFactorU2F`
        """
        model = V2AuthFactorU2F()
        if include_optional:
            return V2AuthFactorU2F(
                id = '69629023906488334',
                name = 'fido key'
            )
        else:
            return V2AuthFactorU2F(
        )
        """

    def testV2AuthFactorU2F(self):
        """Test V2AuthFactorU2F"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
