# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_request_challenges_web_auth_n import V2RequestChallengesWebAuthN

class TestV2RequestChallengesWebAuthN(unittest.TestCase):
    """V2RequestChallengesWebAuthN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2RequestChallengesWebAuthN:
        """Test V2RequestChallengesWebAuthN
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2RequestChallengesWebAuthN`
        """
        model = V2RequestChallengesWebAuthN()
        if include_optional:
            return V2RequestChallengesWebAuthN(
                domain = '',
                user_verification_requirement = 'USER_VERIFICATION_REQUIREMENT_UNSPECIFIED'
            )
        else:
            return V2RequestChallengesWebAuthN(
                domain = '',
                user_verification_requirement = 'USER_VERIFICATION_REQUIREMENT_UNSPECIFIED',
        )
        """

    def testV2RequestChallengesWebAuthN(self):
        """Test V2RequestChallengesWebAuthN"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
