# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.api.session_service_api import SessionServiceApi


class TestSessionServiceApi(unittest.TestCase):
    """SessionServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionServiceApi()

    def tearDown(self) -> None:
        pass

    def test_session_service_create_session(self) -> None:
        """Test case for session_service_create_session

        Create a new session
        """
        pass

    def test_session_service_delete_session(self) -> None:
        """Test case for session_service_delete_session

        Terminate an existing session
        """
        pass

    def test_session_service_get_session(self) -> None:
        """Test case for session_service_get_session

        Get a session
        """
        pass

    def test_session_service_list_sessions(self) -> None:
        """Test case for session_service_list_sessions

        Search sessions
        """
        pass

    def test_session_service_set_session(self) -> None:
        """Test case for session_service_set_session

        Update an existing session
        """
        pass


if __name__ == '__main__':
    unittest.main()
