# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_organization_field_name import V2OrganizationFieldName

class TestV2OrganizationFieldName(unittest.TestCase):
    """V2OrganizationFieldName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2OrganizationFieldName(self):
        """Test V2OrganizationFieldName"""
        # inst = V2OrganizationFieldName()

if __name__ == '__main__':
    unittest.main()
