# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_display_name_query import V2DisplayNameQuery

class TestV2DisplayNameQuery(unittest.TestCase):
    """V2DisplayNameQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2DisplayNameQuery:
        """Test V2DisplayNameQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2DisplayNameQuery`
        """
        model = V2DisplayNameQuery()
        if include_optional:
            return V2DisplayNameQuery(
                display_name = 'Gigi Giraffe',
                method = 'TEXT_QUERY_METHOD_EQUALS'
            )
        else:
            return V2DisplayNameQuery(
                display_name = 'Gigi Giraffe',
        )
        """

    def testV2DisplayNameQuery(self):
        """Test V2DisplayNameQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
