# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_add_organization_response import V2AddOrganizationResponse

class TestV2AddOrganizationResponse(unittest.TestCase):
    """V2AddOrganizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2AddOrganizationResponse:
        """Test V2AddOrganizationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2AddOrganizationResponse`
        """
        model = V2AddOrganizationResponse()
        if include_optional:
            return V2AddOrganizationResponse(
                details = zitadel_client.models.v2_details.v2Details(
                    sequence = '2', 
                    change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_owner = '69629023906488334', ),
                organization_id = '',
                created_admins = [
                    zitadel_client.models.add_organization_response_created_admin.AddOrganizationResponseCreatedAdmin(
                        user_id = '', 
                        email_code = '', 
                        phone_code = '', )
                    ]
            )
        else:
            return V2AddOrganizationResponse(
        )
        """

    def testV2AddOrganizationResponse(self):
        """Test V2AddOrganizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
