# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.otp_email_send_code import OTPEmailSendCode

class TestOTPEmailSendCode(unittest.TestCase):
    """OTPEmailSendCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OTPEmailSendCode:
        """Test OTPEmailSendCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OTPEmailSendCode`
        """
        model = OTPEmailSendCode()
        if include_optional:
            return OTPEmailSendCode(
                url_template = 'https://example.com/otp/verify?userID={{.UserID}}&code={{.Code}}'
            )
        else:
            return OTPEmailSendCode(
        )
        """

    def testOTPEmailSendCode(self):
        """Test OTPEmailSendCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
