# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_get_branding_settings_response import V2GetBrandingSettingsResponse

class TestV2GetBrandingSettingsResponse(unittest.TestCase):
    """V2GetBrandingSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2GetBrandingSettingsResponse:
        """Test V2GetBrandingSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2GetBrandingSettingsResponse`
        """
        model = V2GetBrandingSettingsResponse()
        if include_optional:
            return V2GetBrandingSettingsResponse(
                details = zitadel_client.models.v2_details.v2Details(
                    sequence = '2', 
                    change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_owner = '69629023906488334', ),
                settings = zitadel_client.models.v2_branding_settings.v2BrandingSettings(
                    light_theme = zitadel_client.models.v2_theme.v2Theme(
                        primary_color = '#5469d4', 
                        background_color = '#FAFAFA', 
                        warn_color = '#CD3D56', 
                        font_color = '#000000', 
                        logo_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/logo-180950416321494657', 
                        icon_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/icon-180950498874178817', ), 
                    dark_theme = zitadel_client.models.v2_theme.v2Theme(
                        primary_color = '#5469d4', 
                        background_color = '#FAFAFA', 
                        warn_color = '#CD3D56', 
                        font_color = '#000000', 
                        logo_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/logo-180950416321494657', 
                        icon_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/icon-180950498874178817', ), 
                    font_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/font-180950243237405441', 
                    hide_login_name_suffix = True, 
                    disable_watermark = True, 
                    resource_owner_type = 'RESOURCE_OWNER_TYPE_UNSPECIFIED', 
                    theme_mode = 'THEME_MODE_UNSPECIFIED', )
            )
        else:
            return V2GetBrandingSettingsResponse(
        )
        """

    def testV2GetBrandingSettingsResponse(self):
        """Test V2GetBrandingSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
