# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_theme import V2Theme

class TestV2Theme(unittest.TestCase):
    """V2Theme unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2Theme:
        """Test V2Theme
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2Theme`
        """
        model = V2Theme()
        if include_optional:
            return V2Theme(
                primary_color = '#5469d4',
                background_color = '#FAFAFA',
                warn_color = '#CD3D56',
                font_color = '#000000',
                logo_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/logo-180950416321494657',
                icon_url = 'https://acme.com/assets/v1/165617850692654601/policy/label/icon-180950498874178817'
            )
        else:
            return V2Theme(
        )
        """

    def testV2Theme(self):
        """Test V2Theme"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
