# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_password import V2Password

class TestV2Password(unittest.TestCase):
    """V2Password unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2Password:
        """Test V2Password
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2Password`
        """
        model = V2Password()
        if include_optional:
            return V2Password(
                password = 'Secr3tP4ssw0rd!',
                change_required = True
            )
        else:
            return V2Password(
                password = 'Secr3tP4ssw0rd!',
        )
        """

    def testV2Password(self):
        """Test V2Password"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
