# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.api.settings_api import SettingsApi


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsApi()

    def tearDown(self) -> None:
        pass

    def test_settings_service_get_security_settings(self) -> None:
        """Test case for settings_service_get_security_settings

        Get Security Settings
        """
        pass

    def test_settings_service_set_security_settings(self) -> None:
        """Test case for settings_service_set_security_settings

        Set Security Settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
