# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_ldap_attributes import V2LDAPAttributes

class TestV2LDAPAttributes(unittest.TestCase):
    """V2LDAPAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2LDAPAttributes:
        """Test V2LDAPAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2LDAPAttributes`
        """
        model = V2LDAPAttributes()
        if include_optional:
            return V2LDAPAttributes(
                id_attribute = '',
                first_name_attribute = '',
                last_name_attribute = '',
                display_name_attribute = '',
                nick_name_attribute = '',
                preferred_username_attribute = '',
                email_attribute = '',
                email_verified_attribute = '',
                phone_attribute = '',
                phone_verified_attribute = '',
                preferred_language_attribute = '',
                avatar_url_attribute = '',
                profile_attribute = ''
            )
        else:
            return V2LDAPAttributes(
        )
        """

    def testV2LDAPAttributes(self):
        """Test V2LDAPAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
