# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.zitadelv1_timestamp_query_method import Zitadelv1TimestampQueryMethod

class TestZitadelv1TimestampQueryMethod(unittest.TestCase):
    """Zitadelv1TimestampQueryMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZitadelv1TimestampQueryMethod(self):
        """Test Zitadelv1TimestampQueryMethod"""
        # inst = Zitadelv1TimestampQueryMethod()

if __name__ == '__main__':
    unittest.main()
