# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_creator_query import V2CreatorQuery

class TestV2CreatorQuery(unittest.TestCase):
    """V2CreatorQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2CreatorQuery:
        """Test V2CreatorQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2CreatorQuery`
        """
        model = V2CreatorQuery()
        if include_optional:
            return V2CreatorQuery(
                id = '69629023906488334'
            )
        else:
            return V2CreatorQuery(
        )
        """

    def testV2CreatorQuery(self):
        """Test V2CreatorQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
