# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_set_user_features_response import V2SetUserFeaturesResponse

class TestV2SetUserFeaturesResponse(unittest.TestCase):
    """V2SetUserFeaturesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2SetUserFeaturesResponse:
        """Test V2SetUserFeaturesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2SetUserFeaturesResponse`
        """
        model = V2SetUserFeaturesResponse()
        if include_optional:
            return V2SetUserFeaturesResponse(
                details = zitadel_client.models.v2_details.v2Details(
                    sequence = '2', 
                    change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_owner = '69629023906488334', )
            )
        else:
            return V2SetUserFeaturesResponse(
        )
        """

    def testV2SetUserFeaturesResponse(self):
        """Test V2SetUserFeaturesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
