# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_challenges_web_auth_n import V2ChallengesWebAuthN

class TestV2ChallengesWebAuthN(unittest.TestCase):
    """V2ChallengesWebAuthN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2ChallengesWebAuthN:
        """Test V2ChallengesWebAuthN
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2ChallengesWebAuthN`
        """
        model = V2ChallengesWebAuthN()
        if include_optional:
            return V2ChallengesWebAuthN(
                public_key_credential_request_options = {"publicKey":{"allowCredentials":[{"id":"ATmqBg-99qyOZk2zloPdJQyS2R7IkFT7v9Hoos_B_nM","type":"public-key"}],"challenge":"GAOHYz2jE69kJMYo6Laij8yWw9-dKKgbViNhfuy0StA","rpId":"localhost","timeout":300000,"userVerification":"required"}}
            )
        else:
            return V2ChallengesWebAuthN(
        )
        """

    def testV2ChallengesWebAuthN(self):
        """Test V2ChallengesWebAuthN"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
