# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.user_service_create_invite_code_body import UserServiceCreateInviteCodeBody

class TestUserServiceCreateInviteCodeBody(unittest.TestCase):
    """UserServiceCreateInviteCodeBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserServiceCreateInviteCodeBody:
        """Test UserServiceCreateInviteCodeBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserServiceCreateInviteCodeBody`
        """
        model = UserServiceCreateInviteCodeBody()
        if include_optional:
            return UserServiceCreateInviteCodeBody(
                send_code = zitadel_client.models.v2_send_invite_code.v2SendInviteCode(
                    url_template = 'https://example.com/user/invite?userID={{.UserID}}&code={{.Code}}&orgID={{.OrgID}}', 
                    application_name = 'CustomerPortal', ),
                return_code = None
            )
        else:
            return UserServiceCreateInviteCodeBody(
        )
        """

    def testUserServiceCreateInviteCodeBody(self):
        """Test UserServiceCreateInviteCodeBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
