# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_domain_settings import V2DomainSettings

class TestV2DomainSettings(unittest.TestCase):
    """V2DomainSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2DomainSettings:
        """Test V2DomainSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2DomainSettings`
        """
        model = V2DomainSettings()
        if include_optional:
            return V2DomainSettings(
                login_name_includes_domain = True,
                require_org_domain_verification = True,
                smtp_sender_address_matches_instance_domain = True,
                resource_owner_type = 'RESOURCE_OWNER_TYPE_UNSPECIFIED'
            )
        else:
            return V2DomainSettings(
        )
        """

    def testV2DomainSettings(self):
        """Test V2DomainSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
