# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.api.user_service_api import UserServiceApi


class TestUserServiceApi(unittest.TestCase):
    """UserServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserServiceApi()

    def tearDown(self) -> None:
        pass

    def test_add_human_user(self) -> None:
        """Test case for add_human_user

        Create a new human user
        """
        pass

    def test_add_idp_link(self) -> None:
        """Test case for add_idp_link

        Add link to an identity provider to an user
        """
        pass

    def test_add_otp_email(self) -> None:
        """Test case for add_otp_email

        Add OTP Email for a user
        """
        pass

    def test_add_otpsms(self) -> None:
        """Test case for add_otpsms

        Add OTP SMS for a user
        """
        pass

    def test_create_invite_code(self) -> None:
        """Test case for create_invite_code

        Create an invite code for a user
        """
        pass

    def test_create_passkey_registration_link(self) -> None:
        """Test case for create_passkey_registration_link

        Create a passkey registration link for a user
        """
        pass

    def test_deactivate_user(self) -> None:
        """Test case for deactivate_user

        Deactivate user
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete user
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        User by ID
        """
        pass

    def test_human_mfa_init_skipped(self) -> None:
        """Test case for human_mfa_init_skipped

        MFA Init Skipped
        """
        pass

    def test_list_authentication_factors(self) -> None:
        """Test case for list_authentication_factors

        """
        pass

    def test_list_authentication_method_types(self) -> None:
        """Test case for list_authentication_method_types

        List all possible authentication methods of a user
        """
        pass

    def test_list_idp_links(self) -> None:
        """Test case for list_idp_links

        List links to an identity provider of an user
        """
        pass

    def test_list_passkeys(self) -> None:
        """Test case for list_passkeys

        List passkeys of an user
        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        Search Users
        """
        pass

    def test_lock_user(self) -> None:
        """Test case for lock_user

        Lock user
        """
        pass

    def test_password_reset(self) -> None:
        """Test case for password_reset

        Request a code to reset a password
        """
        pass

    def test_reactivate_user(self) -> None:
        """Test case for reactivate_user

        Reactivate user
        """
        pass

    def test_register_passkey(self) -> None:
        """Test case for register_passkey

        Start the registration of passkey for a user
        """
        pass

    def test_register_totp(self) -> None:
        """Test case for register_totp

        Start the registration of a TOTP generator for a user
        """
        pass

    def test_register_u2_f(self) -> None:
        """Test case for register_u2_f

        Start the registration of a u2f token for a user
        """
        pass

    def test_remove_idp_link(self) -> None:
        """Test case for remove_idp_link

        Remove link of an identity provider to an user
        """
        pass

    def test_remove_otp_email(self) -> None:
        """Test case for remove_otp_email

        Remove One-Time Password (OTP) Email from a user
        """
        pass

    def test_remove_otpsms(self) -> None:
        """Test case for remove_otpsms

        Remove One-Time Password (OTP) SMS from a user
        """
        pass

    def test_remove_passkey(self) -> None:
        """Test case for remove_passkey

        Remove passkey from a user
        """
        pass

    def test_remove_phone(self) -> None:
        """Test case for remove_phone

        Delete the user phone
        """
        pass

    def test_remove_totp(self) -> None:
        """Test case for remove_totp

        Remove TOTP generator from a user
        """
        pass

    def test_remove_u2_f(self) -> None:
        """Test case for remove_u2_f

        Remove u2f token from a user
        """
        pass

    def test_resend_email_code(self) -> None:
        """Test case for resend_email_code

        Resend code to verify user email
        """
        pass

    def test_resend_invite_code(self) -> None:
        """Test case for resend_invite_code

        Resend an invite code for a user
        """
        pass

    def test_resend_phone_code(self) -> None:
        """Test case for resend_phone_code

        Resend code to verify user phone
        """
        pass

    def test_retrieve_identity_provider_intent(self) -> None:
        """Test case for retrieve_identity_provider_intent

        Retrieve the information returned by the identity provider
        """
        pass

    def test_send_email_code(self) -> None:
        """Test case for send_email_code

        Send code to verify user email
        """
        pass

    def test_set_email(self) -> None:
        """Test case for set_email

        Change the user email
        """
        pass

    def test_set_password(self) -> None:
        """Test case for set_password

        Change password
        """
        pass

    def test_set_phone(self) -> None:
        """Test case for set_phone

        Set the user phone
        """
        pass

    def test_start_identity_provider_intent(self) -> None:
        """Test case for start_identity_provider_intent

        Start flow with an identity provider
        """
        pass

    def test_unlock_user(self) -> None:
        """Test case for unlock_user

        Unlock user
        """
        pass

    def test_update_human_user(self) -> None:
        """Test case for update_human_user

        Update User
        """
        pass

    def test_verify_email(self) -> None:
        """Test case for verify_email

        Verify the email
        """
        pass

    def test_verify_invite_code(self) -> None:
        """Test case for verify_invite_code

        Verify an invite code for a user
        """
        pass

    def test_verify_passkey_registration(self) -> None:
        """Test case for verify_passkey_registration

        Verify a passkey for a user
        """
        pass

    def test_verify_phone(self) -> None:
        """Test case for verify_phone

        Verify the phone
        """
        pass

    def test_verify_totp_registration(self) -> None:
        """Test case for verify_totp_registration

        Verify a TOTP generator for a user
        """
        pass

    def test_verify_u2_f_registration(self) -> None:
        """Test case for verify_u2_f_registration

        Verify a u2f token for a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
