# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_passkey import V2Passkey

class TestV2Passkey(unittest.TestCase):
    """V2Passkey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2Passkey:
        """Test V2Passkey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2Passkey`
        """
        model = V2Passkey()
        if include_optional:
            return V2Passkey(
                id = '69629023906488334',
                state = 'AUTH_FACTOR_STATE_UNSPECIFIED',
                name = 'fido key'
            )
        else:
            return V2Passkey(
        )
        """

    def testV2Passkey(self):
        """Test V2Passkey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
