# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_register_u2_f_response import V2RegisterU2FResponse

class TestV2RegisterU2FResponse(unittest.TestCase):
    """V2RegisterU2FResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2RegisterU2FResponse:
        """Test V2RegisterU2FResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2RegisterU2FResponse`
        """
        model = V2RegisterU2FResponse()
        if include_optional:
            return V2RegisterU2FResponse(
                details = zitadel_client.models.v2_details.v2Details(
                    sequence = '2', 
                    change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_owner = '69629023906488334', ),
                u2f_id = '163840776835432705',
                public_key_credential_creation_options = {"publicKey":{"attestation":"none","authenticatorSelection":{"userVerification":"required"},"challenge":"XaMYwWOZ5hj6pwtwJJlpcI-ExkO5TxevBMG4R8DoKQQ","excludeCredentials":[{"id":"tVp1QfYhT8DkyEHVrv7blnpAo2YJzbZgZNBf7zPs6CI","type":"public-key"}],"pubKeyCredParams":[{"alg":-7,"type":"public-key"}],"rp":{"id":"localhost","name":"ZITADEL"},"timeout":300000,"user":{"displayName":"Tim Mohlmann","id":"MjE1NTk4MDAwNDY0OTk4OTQw","name":"tim"}}}
            )
        else:
            return V2RegisterU2FResponse(
        )
        """

    def testV2RegisterU2FResponse(self):
        """Test V2RegisterU2FResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
