# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_remove_u2_f_response import V2RemoveU2FResponse

class TestV2RemoveU2FResponse(unittest.TestCase):
    """V2RemoveU2FResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2RemoveU2FResponse:
        """Test V2RemoveU2FResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2RemoveU2FResponse`
        """
        model = V2RemoveU2FResponse()
        if include_optional:
            return V2RemoveU2FResponse(
                details = zitadel_client.models.v2_details.v2Details(
                    sequence = '2', 
                    change_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    resource_owner = '69629023906488334', )
            )
        else:
            return V2RemoveU2FResponse(
        )
        """

    def testV2RemoveU2FResponse(self):
        """Test V2RemoveU2FResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
