# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zitadel_client.models.v2_idp_intent import V2IDPIntent

class TestV2IDPIntent(unittest.TestCase):
    """V2IDPIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2IDPIntent:
        """Test V2IDPIntent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2IDPIntent`
        """
        model = V2IDPIntent()
        if include_optional:
            return V2IDPIntent(
                idp_intent_id = '163840776835432705',
                idp_intent_token = 'SJKL3ioIDpo342ioqw98fjp3sdf32wahb=',
                user_id = '163840776835432345'
            )
        else:
            return V2IDPIntent(
        )
        """

    def testV2IDPIntent(self):
        """Test V2IDPIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
