version: 2
updates:
    - package-ecosystem: "python"
      schedule:
          interval: "weekly"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
