# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

import asyncio
from typing import Any, Dict, List, Optional, TypeVar
from urllib.parse import urlencode

from ..api_client import ApiClient
from ..api_response import ApiHttpResponse
from ..api_result import ApiResult
from ..default_api_client import DefaultApiClient
from ..configuration import Configuration
from ..object_serializer import ObjectSerializer
from ..header_selector import HeaderSelector
from ..trace_context_util import inject_trace_context
from ..errors import ApiException
from ..errors.client_exception import ClientException
from ..errors.server_exception import ServerException
from ..errors.bad_request_exception import BadRequestException
from ..errors.unauthorized_exception import UnauthorizedException
from ..errors.forbidden_exception import ForbiddenException
from ..errors.not_found_exception import NotFoundException
from ..errors.conflict_exception import ConflictException
from ..errors.unprocessable_entity_exception import UnprocessableEntityException
from ..errors.internal_server_error_exception import InternalServerErrorException
from ..auth.authenticator import Authenticator

T = TypeVar("T")

_COOKIE_NAME_CHARS = frozenset(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#$%&'*+-.^_`|~"
)


def _is_valid_cookie_name(name: str) -> bool:
    """RFC 6265 cookie-name validation (RFC 7230 token)."""
    if not name:
        return False
    return all(c in _COOKIE_NAME_CHARS for c in name)


def _is_valid_cookie_value(value: str) -> bool:
    """RFC 6265 cookie-value validation (cookie-octet*)."""
    for c in value:
        code = ord(c)
        if not (
            code == 0x21
            or 0x23 <= code <= 0x2B
            or 0x2D <= code <= 0x3A
            or 0x3C <= code <= 0x5B
            or 0x5D <= code <= 0x7E
        ):
            return False
    return True


class BaseApi:
    """Base class for all API classes.

    Provides the invoke_api method that handles URL construction, header
    selection, body serialization, request dispatch, and response
    deserialization.
    """

    def __init__(
        self,
        api_client: Optional[ApiClient] = None,
        config: Optional[Configuration] = None,
        authenticator: Optional[Authenticator] = None,
    ):
        """Create an API instance.

        When called with no arguments, uses the default configuration and
        a default-constructed :class:`DefaultApiClient` (with default
        transport settings).

        When called with a configuration only, creates a
        :class:`DefaultApiClient` with default transport settings.

        When called with both an api_client and config, uses the provided
        instances directly (this is the path used by :class:`Client`).

        Args:
            api_client: The HTTP transport client. If ``None``, a
                :class:`DefaultApiClient` with default transport is created.
            config: API-level configuration (base URL and default headers).
                If ``None``, the default configuration is used.
        """
        self._config = config or Configuration.get_default()
        self._api_client = api_client or DefaultApiClient()
        self._authenticator = authenticator
        self._object_serializer = ObjectSerializer()
        self._header_selector = HeaderSelector()

    async def _invoke_api_for_result(
        self,
        method: str,
        path: str,
        query_params: Dict[str, Any],
        header_params: Dict[str, str],
        body: Any,
        accepts: List[str],
        content_type: Optional[str],
        return_type: Optional[str],
        auth: Optional[Authenticator] = None,
    ) -> "ApiResult[Any]":
        """Invoke an API operation and return the full result.

        Args:
            method: HTTP method (GET, POST, PUT, DELETE, etc.).
            path: URL path (with path params already substituted).
            query_params: Query parameters.
            header_params: Custom header parameters.
            body: Request body (model object or None).
            accepts: Acceptable response content types.
            content_type: Request content type.
            return_type: Return type for deserialization (None for void).
            auth: Optional authenticator for operation-specific auth.

        Returns:
            ApiResult containing deserialized data, status code, raw body,
            and headers.

        Raises:
            ApiException: If the API call fails.
        """
        if path.startswith("http://") or path.startswith("https://"):
            url = path
        else:
            # Strip trailing slash from baseUrl when path starts with `/`
            # so baseUrl='https://x/' + path='/y' produces 'https://x/y',
            # not 'https://x//y' which most servers route to 404. Matches
            # Java/C#/Go/Swift/Dart/Kotlin which collapse via URI parsers.
            url = (
                self._config.base_url.rstrip("/") + path
                if path.startswith("/")
                else self._config.base_url + path
            )

        effective_auth = auth if auth is not None else self._authenticator

        if effective_auth is not None:
            query_params.update(effective_auth.get_query_params())

        if query_params:
            filtered = {k: v for k, v in query_params.items() if v is not None}
            if filtered:
                normalized: dict[str, str | list[str]] = {}
                for k, v in filtered.items():
                    if isinstance(v, list):
                        normalized[k] = [
                            self._object_serializer.stringify(item) for item in v
                        ]
                    else:
                        normalized[k] = self._object_serializer.stringify(v)
                url += "?" + urlencode(normalized, doseq=True)

        is_multipart = content_type == "multipart/form-data"
        headers = self._header_selector.select_headers(
            accepts, content_type or "", is_multipart
        )
        headers.update(self._config.default_headers)
        if header_params:
            headers.update(header_params)
        if effective_auth is not None:
            headers.update(effective_auth.get_auth_headers())
            cookies = effective_auth.get_cookie_params()
            if cookies:
                # RFC 6265 — don't URL-encode cookie name/value; most cookie
                # parsers don't URL-decode, so `=` (base64 padding) would
                # arrive as literal `%3D` and break JWT/session cookies.
                # Validate and pass through raw instead.
                cookie_parts = []
                for k, v in cookies.items():
                    name = str(k)
                    value = str(v)
                    if not _is_valid_cookie_name(name):
                        raise ValueError(
                            f"Cookie name '{name}' contains characters forbidden by RFC 6265"
                        )
                    if not _is_valid_cookie_value(value):
                        raise ValueError(
                            f"Cookie value for '{name}' contains characters forbidden by RFC 6265"
                        )
                    cookie_parts.append(f"{name}={value}")
                cookie_str = "; ".join(cookie_parts)
                existing = headers.get("Cookie", "")
                if existing:
                    headers["Cookie"] = existing + "; " + cookie_str
                else:
                    headers["Cookie"] = cookie_str
        inject_trace_context(headers)

        # Remove Content-Type when there is no body (semantically wrong to send it)
        if body is None:
            headers.pop("Content-Type", None)

        serialized_body = None
        if body is not None:
            if content_type == "multipart/form-data":
                serialized_body = body
            elif content_type is not None and (
                content_type.startswith("image/")
                or content_type == "application/octet-stream"
            ):
                serialized_body = body
            elif content_type == "text/plain":
                serialized_body = str(body)
            elif content_type == "application/x-www-form-urlencoded":
                # Build a (key, value) pair list so array values become
                # repeated keys (`tags=a&tags=b`) rather than a single
                # `tags=['a', 'b']` Python-repr. Each scalar is stringified
                # through ObjectSerializer so bools render as `true`/`false`
                # and enums/dates use their wire form, matching the other
                # SDKs. None-valued fields are omitted, and None elements
                # inside an array are skipped. urlencode(..., doseq=True)
                # then percent-encodes with `quote_plus`, so a space becomes
                # `+` (HTML form encoding), not `%20`.
                form_pairs: List[tuple[str, str]] = []
                for form_key, form_value in body.items():
                    if form_value is None:
                        continue
                    if isinstance(form_value, list):
                        for form_item in form_value:
                            if form_item is None:
                                continue
                            form_pairs.append(
                                (form_key, self._object_serializer.stringify(form_item))
                            )
                    else:
                        form_pairs.append(
                            (form_key, self._object_serializer.stringify(form_value))
                        )
                serialized_body = urlencode(form_pairs, doseq=True)
            else:
                serialized_body = self._object_serializer.serialize(body)

        response = await asyncio.to_thread(
            self._api_client.send_request, method, url, headers, serialized_body
        )

        if response.status_code < 200 or response.status_code >= 300:
            self._throw_api_exception(response)

        data: Any = None
        if return_type is not None and response.body:
            resp_content_type = ""
            for k, v in response.headers.items():
                if k.lower() == "content-type":
                    resp_content_type = v.split(";")[0].strip()
                    break
            if resp_content_type and not self._header_selector.is_json_mime(
                resp_content_type
            ):
                if return_type == "bytes":
                    import base64

                    data = base64.b64decode(response.body) if response.body else b""
                else:
                    data = response.body
            else:
                data = self._object_serializer.deserialize(response.body, return_type)

        return ApiResult(
            status_code=response.status_code,
            data=data,
            raw_body=response.body,
            headers=response.headers,
        )

    async def _invoke_api(
        self,
        method: str,
        path: str,
        query_params: Dict[str, Any],
        header_params: Dict[str, str],
        body: Any,
        accepts: List[str],
        content_type: Optional[str],
        return_type: Optional[str],
        auth: Optional[Authenticator] = None,
    ) -> Any:
        """Invoke an API operation.

        Args:
            method: HTTP method (GET, POST, PUT, DELETE, etc.).
            path: URL path (with path params already substituted).
            query_params: Query parameters.
            header_params: Custom header parameters.
            body: Request body (model object or None).
            accepts: Acceptable response content types.
            content_type: Request content type.
            return_type: Return type for deserialization (None for void).
            auth: Optional authenticator for operation-specific auth.

        Returns:
            Deserialized response or None.

        Raises:
            ApiException: If the API call fails.
        """
        result = await self._invoke_api_for_result(
            method,
            path,
            query_params,
            header_params,
            body,
            accepts,
            content_type,
            return_type,
            auth,
        )
        return result.data

    @staticmethod
    def _throw_api_exception(response: "ApiHttpResponse") -> None:
        """Throw the appropriate exception subclass for the given error response.

        Attempts to parse the response body as JSON so that structured error
        data (e.g. from a ``default`` response schema) is available via
        :attr:`ApiException.error_body`.
        """
        import json as _json

        code = response.status_code
        message = f"API returned status code {code}"
        body = response.body
        # Pass response headers through unconditionally. An empty header map is
        # a real (if unusual) error response, distinct from "no response" --
        # coercing empty headers to None conflated the two and dropped a valid
        # empty dict. The transport always supplies a dict here.
        headers = dict(response.headers)

        error_body = None
        if body:
            try:
                error_body = _json.loads(body)
            except (ValueError, TypeError):
                pass

        if 400 <= code < 500:
            if code == 400:
                raise BadRequestException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            if code == 401:
                raise UnauthorizedException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            if code == 403:
                raise ForbiddenException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            if code == 404:
                raise NotFoundException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            if code == 409:
                raise ConflictException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            if code == 422:
                raise UnprocessableEntityException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            raise ClientException(
                status_code=code,
                message=message,
                response_body=body,
                response_headers=headers,
                error_body=error_body,
            )
        if code >= 500:
            if code == 500:
                raise InternalServerErrorException(
                    message=message,
                    response_body=body,
                    response_headers=headers,
                    error_body=error_body,
                )
            raise ServerException(
                status_code=code,
                message=message,
                response_body=body,
                response_headers=headers,
                error_body=error_body,
            )
        raise ApiException(
            status_code=code,
            message=message,
            response_body=body,
            response_headers=headers,
            error_body=error_body,
        )
