# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from typing import Any, Dict, List, Optional
from pydantic import StrictBool, StrictFloat, StrictInt, StrictStr

from zitadel_client.models.settings_service_connect_error import (
    SettingsServiceConnectError,
)
from zitadel_client.models.settings_service_get_active_identity_providers_request import (
    SettingsServiceGetActiveIdentityProvidersRequest,
)
from zitadel_client.models.settings_service_get_active_identity_providers_response import (
    SettingsServiceGetActiveIdentityProvidersResponse,
)
from zitadel_client.models.settings_service_get_branding_settings_request import (
    SettingsServiceGetBrandingSettingsRequest,
)
from zitadel_client.models.settings_service_get_branding_settings_response import (
    SettingsServiceGetBrandingSettingsResponse,
)
from zitadel_client.models.settings_service_get_domain_settings_request import (
    SettingsServiceGetDomainSettingsRequest,
)
from zitadel_client.models.settings_service_get_domain_settings_response import (
    SettingsServiceGetDomainSettingsResponse,
)
from zitadel_client.models.settings_service_get_general_settings_response import (
    SettingsServiceGetGeneralSettingsResponse,
)
from zitadel_client.models.settings_service_get_hosted_login_translation_request import (
    SettingsServiceGetHostedLoginTranslationRequest,
)
from zitadel_client.models.settings_service_get_hosted_login_translation_response import (
    SettingsServiceGetHostedLoginTranslationResponse,
)
from zitadel_client.models.settings_service_get_legal_and_support_settings_request import (
    SettingsServiceGetLegalAndSupportSettingsRequest,
)
from zitadel_client.models.settings_service_get_legal_and_support_settings_response import (
    SettingsServiceGetLegalAndSupportSettingsResponse,
)
from zitadel_client.models.settings_service_get_lockout_settings_request import (
    SettingsServiceGetLockoutSettingsRequest,
)
from zitadel_client.models.settings_service_get_lockout_settings_response import (
    SettingsServiceGetLockoutSettingsResponse,
)
from zitadel_client.models.settings_service_get_login_settings_request import (
    SettingsServiceGetLoginSettingsRequest,
)
from zitadel_client.models.settings_service_get_login_settings_response import (
    SettingsServiceGetLoginSettingsResponse,
)
from zitadel_client.models.settings_service_get_password_complexity_settings_request import (
    SettingsServiceGetPasswordComplexitySettingsRequest,
)
from zitadel_client.models.settings_service_get_password_complexity_settings_response import (
    SettingsServiceGetPasswordComplexitySettingsResponse,
)
from zitadel_client.models.settings_service_get_password_expiry_settings_request import (
    SettingsServiceGetPasswordExpirySettingsRequest,
)
from zitadel_client.models.settings_service_get_password_expiry_settings_response import (
    SettingsServiceGetPasswordExpirySettingsResponse,
)
from zitadel_client.models.settings_service_get_security_settings_response import (
    SettingsServiceGetSecuritySettingsResponse,
)
from zitadel_client.models.settings_service_set_hosted_login_translation_request import (
    SettingsServiceSetHostedLoginTranslationRequest,
)
from zitadel_client.models.settings_service_set_hosted_login_translation_response import (
    SettingsServiceSetHostedLoginTranslationResponse,
)
from zitadel_client.models.settings_service_set_security_settings_request import (
    SettingsServiceSetSecuritySettingsRequest,
)
from zitadel_client.models.settings_service_set_security_settings_response import (
    SettingsServiceSetSecuritySettingsResponse,
)

from ..api_client import ApiClient
from ..api_result import ApiResult
from ..configuration import Configuration
from .base_api import BaseApi
from ..value_serializer import ValueSerializer
from ..auth.authenticator import Authenticator
from ..errors import ApiException


class SettingsServiceApi(BaseApi):
    """SettingsServiceApi provides methods for the SettingsService API group."""

    def __init__(
        self,
        api_client: Optional[ApiClient] = None,
        config: Optional[Configuration] = None,
        authenticator: Optional[Authenticator] = None,
    ):
        super().__init__(api_client, config, authenticator)

    async def get_active_identity_providers(
        self,
        settings_service_get_active_identity_providers_request: SettingsServiceGetActiveIdentityProvidersRequest,
    ) -> SettingsServiceGetActiveIdentityProvidersResponse:
        """Get Active Identity Providers
        Get the current active identity providers for the requested context.  This can be the instance or an organization. In case of an organization,  the returned identity providers will fall back to the active instance identity providers  if not explicitly set on the organization.   Optionally, filter the identity providers by their allowed actions:    - creation_allowed: only return identity providers that are allowed for user creation    - linking_allowed: only return identity providers that are allowed for linking to existing users    - auto_creation: only return identity providers that are allowed for automatic user creation    - auto_linking: only return identity providers that are allowed for automatic linking to existing users   Required permissions:    - `policy.read`
        :param settings_service_get_active_identity_providers_request:  (required)

        :return: SettingsServiceGetActiveIdentityProvidersResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_active_identity_providers_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_active_identity_providers_request'"
            )

        result = await self.get_active_identity_providers_with_http_info(
            settings_service_get_active_identity_providers_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_active_identity_providers_with_http_info(
        self,
        settings_service_get_active_identity_providers_request: SettingsServiceGetActiveIdentityProvidersRequest,
    ) -> "ApiResult[SettingsServiceGetActiveIdentityProvidersResponse]":
        """Get Active Identity Providers (with HTTP info)
        Get the current active identity providers for the requested context.  This can be the instance or an organization. In case of an organization,  the returned identity providers will fall back to the active instance identity providers  if not explicitly set on the organization.   Optionally, filter the identity providers by their allowed actions:    - creation_allowed: only return identity providers that are allowed for user creation    - linking_allowed: only return identity providers that are allowed for linking to existing users    - auto_creation: only return identity providers that are allowed for automatic user creation    - auto_linking: only return identity providers that are allowed for automatic linking to existing users   Required permissions:    - `policy.read`
        :param settings_service_get_active_identity_providers_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_active_identity_providers_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_active_identity_providers_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetActiveIdentityProviders"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_active_identity_providers_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetActiveIdentityProvidersResponse",
            None,
        )

    async def get_branding_settings(
        self,
        settings_service_get_branding_settings_request: SettingsServiceGetBrandingSettingsRequest,
    ) -> SettingsServiceGetBrandingSettingsResponse:
        """Get Branding Settings
        Get the current active branding settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_branding_settings_request:  (required)

        :return: SettingsServiceGetBrandingSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_branding_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_branding_settings_request'"
            )

        result = await self.get_branding_settings_with_http_info(
            settings_service_get_branding_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_branding_settings_with_http_info(
        self,
        settings_service_get_branding_settings_request: SettingsServiceGetBrandingSettingsRequest,
    ) -> "ApiResult[SettingsServiceGetBrandingSettingsResponse]":
        """Get Branding Settings (with HTTP info)
        Get the current active branding settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_branding_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_branding_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_branding_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetBrandingSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_branding_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetBrandingSettingsResponse",
            None,
        )

    async def get_domain_settings(
        self,
        settings_service_get_domain_settings_request: SettingsServiceGetDomainSettingsRequest,
    ) -> SettingsServiceGetDomainSettingsResponse:
        """Get Domain Settings
        Get the domain settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_domain_settings_request:  (required)

        :return: SettingsServiceGetDomainSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_domain_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_domain_settings_request'"
            )

        result = await self.get_domain_settings_with_http_info(
            settings_service_get_domain_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_domain_settings_with_http_info(
        self,
        settings_service_get_domain_settings_request: SettingsServiceGetDomainSettingsRequest,
    ) -> "ApiResult[SettingsServiceGetDomainSettingsResponse]":
        """Get Domain Settings (with HTTP info)
        Get the domain settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_domain_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_domain_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_domain_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetDomainSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_domain_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetDomainSettingsResponse",
            None,
        )

    async def get_general_settings(
        self,
        body: object,
    ) -> SettingsServiceGetGeneralSettingsResponse:
        """Get General Settings
        Get basic information of the instance like the default organization, default language and supported languages.   Required permissions:    - `policy.read`
        :param body:  (required)

        :return: SettingsServiceGetGeneralSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if body is None:
            raise ValueError("Missing the required parameter 'body'")

        result = await self.get_general_settings_with_http_info(body)

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_general_settings_with_http_info(
        self,
        body: object,
    ) -> "ApiResult[SettingsServiceGetGeneralSettingsResponse]":
        """Get General Settings (with HTTP info)
        Get basic information of the instance like the default organization, default language and supported languages.   Required permissions:    - `policy.read`
        :param body:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if body is None:
            raise ValueError("Missing the required parameter 'body'")

        path = "/zitadel.settings.v2.SettingsService/GetGeneralSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = body

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetGeneralSettingsResponse",
            None,
        )

    async def get_hosted_login_translation(
        self,
        settings_service_get_hosted_login_translation_request: SettingsServiceGetHostedLoginTranslationRequest,
    ) -> SettingsServiceGetHostedLoginTranslationResponse:
        """Get Hosted Login Translation
        Returns the translations in the requested locale for the hosted login.  The translations returned are based on the input level specified (system, instance or organization).   If the requested level doesn't contain all translations, and ignore_inheritance is set to false,  a merging process fallbacks onto the higher levels ensuring all keys in the file have a translation,  which could be in the default language if the one of the locale is missing on all levels.   The etag returned in the response represents the hash of the translations as they are stored on DB  and its reliable only if ignore_inheritance = true.   Required permissions:    - `iam.policy.read`
        :param settings_service_get_hosted_login_translation_request:  (required)

        :return: SettingsServiceGetHostedLoginTranslationResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_hosted_login_translation_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_hosted_login_translation_request'"
            )

        result = await self.get_hosted_login_translation_with_http_info(
            settings_service_get_hosted_login_translation_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_hosted_login_translation_with_http_info(
        self,
        settings_service_get_hosted_login_translation_request: SettingsServiceGetHostedLoginTranslationRequest,
    ) -> "ApiResult[SettingsServiceGetHostedLoginTranslationResponse]":
        """Get Hosted Login Translation (with HTTP info)
        Returns the translations in the requested locale for the hosted login.  The translations returned are based on the input level specified (system, instance or organization).   If the requested level doesn't contain all translations, and ignore_inheritance is set to false,  a merging process fallbacks onto the higher levels ensuring all keys in the file have a translation,  which could be in the default language if the one of the locale is missing on all levels.   The etag returned in the response represents the hash of the translations as they are stored on DB  and its reliable only if ignore_inheritance = true.   Required permissions:    - `iam.policy.read`
        :param settings_service_get_hosted_login_translation_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_hosted_login_translation_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_hosted_login_translation_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetHostedLoginTranslation"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_hosted_login_translation_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetHostedLoginTranslationResponse",
            None,
        )

    async def get_legal_and_support_settings(
        self,
        settings_service_get_legal_and_support_settings_request: SettingsServiceGetLegalAndSupportSettingsRequest,
    ) -> SettingsServiceGetLegalAndSupportSettingsResponse:
        """Get Legal and Support Settings
        Get the legal and support settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_legal_and_support_settings_request:  (required)

        :return: SettingsServiceGetLegalAndSupportSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_legal_and_support_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_legal_and_support_settings_request'"
            )

        result = await self.get_legal_and_support_settings_with_http_info(
            settings_service_get_legal_and_support_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_legal_and_support_settings_with_http_info(
        self,
        settings_service_get_legal_and_support_settings_request: SettingsServiceGetLegalAndSupportSettingsRequest,
    ) -> "ApiResult[SettingsServiceGetLegalAndSupportSettingsResponse]":
        """Get Legal and Support Settings (with HTTP info)
        Get the legal and support settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_legal_and_support_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_legal_and_support_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_legal_and_support_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetLegalAndSupportSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_legal_and_support_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetLegalAndSupportSettingsResponse",
            None,
        )

    async def get_lockout_settings(
        self,
        settings_service_get_lockout_settings_request: SettingsServiceGetLockoutSettingsRequest,
    ) -> SettingsServiceGetLockoutSettingsResponse:
        """Get Lockout Settings
        Get the lockout settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Lockout settings define how many failed attempts are allowed before a user is locked out.   Required permissions:    - `policy.read`
        :param settings_service_get_lockout_settings_request:  (required)

        :return: SettingsServiceGetLockoutSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_lockout_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_lockout_settings_request'"
            )

        result = await self.get_lockout_settings_with_http_info(
            settings_service_get_lockout_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_lockout_settings_with_http_info(
        self,
        settings_service_get_lockout_settings_request: SettingsServiceGetLockoutSettingsRequest,
    ) -> "ApiResult[SettingsServiceGetLockoutSettingsResponse]":
        """Get Lockout Settings (with HTTP info)
        Get the lockout settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Lockout settings define how many failed attempts are allowed before a user is locked out.   Required permissions:    - `policy.read`
        :param settings_service_get_lockout_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_lockout_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_lockout_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetLockoutSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_lockout_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetLockoutSettingsResponse",
            None,
        )

    async def get_login_settings(
        self,
        settings_service_get_login_settings_request: SettingsServiceGetLoginSettingsRequest,
    ) -> SettingsServiceGetLoginSettingsResponse:
        """Get Login Settings
        Get the login settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_login_settings_request:  (required)

        :return: SettingsServiceGetLoginSettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_login_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_login_settings_request'"
            )

        result = await self.get_login_settings_with_http_info(
            settings_service_get_login_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_login_settings_with_http_info(
        self,
        settings_service_get_login_settings_request: SettingsServiceGetLoginSettingsRequest,
    ) -> "ApiResult[SettingsServiceGetLoginSettingsResponse]":
        """Get Login Settings (with HTTP info)
        Get the login settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_login_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_login_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_login_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetLoginSettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_login_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetLoginSettingsResponse",
            None,
        )

    async def get_password_complexity_settings(
        self,
        settings_service_get_password_complexity_settings_request: SettingsServiceGetPasswordComplexitySettingsRequest,
    ) -> SettingsServiceGetPasswordComplexitySettingsResponse:
        """Get Password Complexity Settings
        Get the password complexity settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_password_complexity_settings_request:  (required)

        :return: SettingsServiceGetPasswordComplexitySettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_password_complexity_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_password_complexity_settings_request'"
            )

        result = await self.get_password_complexity_settings_with_http_info(
            settings_service_get_password_complexity_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_password_complexity_settings_with_http_info(
        self,
        settings_service_get_password_complexity_settings_request: SettingsServiceGetPasswordComplexitySettingsRequest,
    ) -> "ApiResult[SettingsServiceGetPasswordComplexitySettingsResponse]":
        """Get Password Complexity Settings (with HTTP info)
        Get the password complexity settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_password_complexity_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_password_complexity_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_password_complexity_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetPasswordComplexitySettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_password_complexity_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetPasswordComplexitySettingsResponse",
            None,
        )

    async def get_password_expiry_settings(
        self,
        settings_service_get_password_expiry_settings_request: SettingsServiceGetPasswordExpirySettingsRequest,
    ) -> SettingsServiceGetPasswordExpirySettingsResponse:
        """Get Password Expiry Settings
        Get the password expiry settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_password_expiry_settings_request:  (required)

        :return: SettingsServiceGetPasswordExpirySettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_password_expiry_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_password_expiry_settings_request'"
            )

        result = await self.get_password_expiry_settings_with_http_info(
            settings_service_get_password_expiry_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_password_expiry_settings_with_http_info(
        self,
        settings_service_get_password_expiry_settings_request: SettingsServiceGetPasswordExpirySettingsRequest,
    ) -> "ApiResult[SettingsServiceGetPasswordExpirySettingsResponse]":
        """Get Password Expiry Settings (with HTTP info)
        Get the password expiry settings for the requested context.  This can be the instance or an organization. In case of an organization,  the returned settings will fall back to the instance settings if not explicitly set on the organization.   Required permissions:    - `policy.read`
        :param settings_service_get_password_expiry_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_get_password_expiry_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_get_password_expiry_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/GetPasswordExpirySettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_get_password_expiry_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetPasswordExpirySettingsResponse",
            None,
        )

    async def get_security_settings(
        self,
        body: object,
    ) -> SettingsServiceGetSecuritySettingsResponse:
        """Get Security Settings
        Get the security settings of the ZITADEL instance.  Security settings include settings like enabling impersonation and embedded iframe settings.   Required permissions:    - `iam.policy.read`
        :param body:  (required)

        :return: SettingsServiceGetSecuritySettingsResponse
        :raises ApiException: if fails to make API call
        """
        if body is None:
            raise ValueError("Missing the required parameter 'body'")

        result = await self.get_security_settings_with_http_info(body)

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def get_security_settings_with_http_info(
        self,
        body: object,
    ) -> "ApiResult[SettingsServiceGetSecuritySettingsResponse]":
        """Get Security Settings (with HTTP info)
        Get the security settings of the ZITADEL instance.  Security settings include settings like enabling impersonation and embedded iframe settings.   Required permissions:    - `iam.policy.read`
        :param body:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if body is None:
            raise ValueError("Missing the required parameter 'body'")

        path = "/zitadel.settings.v2.SettingsService/GetSecuritySettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = body

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceGetSecuritySettingsResponse",
            None,
        )

    async def set_hosted_login_translation(
        self,
        settings_service_set_hosted_login_translation_request: SettingsServiceSetHostedLoginTranslationRequest,
    ) -> SettingsServiceSetHostedLoginTranslationResponse:
        """Set Hosted Login Translation
        Sets the input translations at the specified level (instance or organization) for the input language.   Required permissions:    - `iam.policy.write`
        :param settings_service_set_hosted_login_translation_request:  (required)

        :return: SettingsServiceSetHostedLoginTranslationResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_set_hosted_login_translation_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_set_hosted_login_translation_request'"
            )

        result = await self.set_hosted_login_translation_with_http_info(
            settings_service_set_hosted_login_translation_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def set_hosted_login_translation_with_http_info(
        self,
        settings_service_set_hosted_login_translation_request: SettingsServiceSetHostedLoginTranslationRequest,
    ) -> "ApiResult[SettingsServiceSetHostedLoginTranslationResponse]":
        """Set Hosted Login Translation (with HTTP info)
        Sets the input translations at the specified level (instance or organization) for the input language.   Required permissions:    - `iam.policy.write`
        :param settings_service_set_hosted_login_translation_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_set_hosted_login_translation_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_set_hosted_login_translation_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/SetHostedLoginTranslation"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_set_hosted_login_translation_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceSetHostedLoginTranslationResponse",
            None,
        )

    async def set_security_settings(
        self,
        settings_service_set_security_settings_request: SettingsServiceSetSecuritySettingsRequest,
    ) -> SettingsServiceSetSecuritySettingsResponse:
        """Set Security Settings
        Set the security settings of the instance.   Required permissions:    - `iam.policy.write`
        :param settings_service_set_security_settings_request:  (required)

        :return: SettingsServiceSetSecuritySettingsResponse
        :raises ApiException: if fails to make API call
        """
        if settings_service_set_security_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_set_security_settings_request'"
            )

        result = await self.set_security_settings_with_http_info(
            settings_service_set_security_settings_request
        )

        if result.data is None:
            # This operation declares a non-void return type, so an empty /
            # undecodable response body is a contract violation. Raise the
            # SDK's typed ApiException (rather than an assert that vanishes
            # under -O, or a silent None) so callers get one catchable error.
            raise ApiException(
                status_code=result.status_code,
                message="Expected a response body but the server returned none",
                response_body=result.raw_body,
                response_headers=result.headers,
            )
        return result.data

    async def set_security_settings_with_http_info(
        self,
        settings_service_set_security_settings_request: SettingsServiceSetSecuritySettingsRequest,
    ) -> "ApiResult[SettingsServiceSetSecuritySettingsResponse]":
        """Set Security Settings (with HTTP info)
        Set the security settings of the instance.   Required permissions:    - `iam.policy.write`
        :param settings_service_set_security_settings_request:  (required)

        :return: ApiResult containing the response data, status code, raw body, and headers
        :raises ApiException: if fails to make API call
        """
        if settings_service_set_security_settings_request is None:
            raise ValueError(
                "Missing the required parameter 'settings_service_set_security_settings_request'"
            )

        path = "/zitadel.settings.v2.SettingsService/SetSecuritySettings"
        query_params: Dict[str, Any] = {}
        header_params: Dict[str, str] = {}
        body = settings_service_set_security_settings_request

        return await self._invoke_api_for_result(
            "POST",
            path,
            query_params,
            header_params,
            body,
            ["application/json"],
            "application/json",
            "SettingsServiceSetSecuritySettingsResponse",
            None,
        )
