# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

from dataclasses import dataclass, field
from types import MappingProxyType
from typing import ClassVar, Dict, Mapping, Optional

from typing_extensions import Self

from .server_configuration import ServerConfiguration


@dataclass(frozen=True)
class Configuration:
    """API-level configuration for generated client classes.

    Holds the base URL and default headers that are applied to every API
    request. Transport-level settings (TLS, proxy, timeouts) belong in
    :class:`TransportOptions` and are configured on the
    :class:`DefaultApiClient`.

    This class is immutable and thread-safe. Use :meth:`builder` to create
    instances::

        config = Configuration.builder() \\
            .base_url('https://api.example.com') \\
            .default_header('Authorization', 'Bearer token') \\
            .build()
    """

    base_url: str = "https://zitadel.com"
    """The base URL for all API requests.

    Defaults to the first server URL from the OpenAPI specification.
    """

    default_headers: Mapping[str, str] = field(
        default_factory=lambda: MappingProxyType({})
    )
    """Default headers included in every API request.

    These headers are merged after transport-level headers from
    :class:`TransportOptions` but before operation-specific headers
    and authentication headers.
    """

    _default: ClassVar[Optional["Configuration"]] = None

    def __post_init__(self) -> None:
        if not isinstance(self.default_headers, MappingProxyType):
            object.__setattr__(
                self, "default_headers", MappingProxyType(dict(self.default_headers))
            )

    @classmethod
    def get_default(cls) -> "Configuration":
        """Return the default configuration instance, creating it lazily if needed."""
        if cls._default is None:
            cls._default = cls()
        return cls._default

    @classmethod
    def set_default(cls, configuration: Optional[Self]) -> None:
        """Set the default configuration instance."""
        cls._default = configuration

    @classmethod
    def builder(cls) -> "ConfigurationBuilder":
        """Create a new builder for constructing Configuration instances."""
        return ConfigurationBuilder()


class ConfigurationBuilder:
    """Builder for creating immutable :class:`Configuration` instances.

    Example::

        config = Configuration.builder() \\
            .base_url('https://api.example.com') \\
            .default_header('X-Custom', 'value') \\
            .build()
    """

    def __init__(self) -> None:
        self._base_url: str = "https://zitadel.com"
        self._default_headers: Dict[str, str] = {}

    def base_url(self, base_url: str) -> "ConfigurationBuilder":
        """Set the base URL for all API requests.

        Args:
            base_url: The base URL.

        Returns:
            This builder.
        """
        self._base_url = base_url
        return self

    def default_header(self, name: str, value: str) -> "ConfigurationBuilder":
        """Add a single default header to include in every API request.

        Args:
            name: Header name.
            value: Header value.

        Returns:
            This builder.
        """
        self._default_headers[name] = value
        return self

    def server(
        self,
        server_config: ServerConfiguration,
        variables: Optional[Dict[str, str]] = None,
    ) -> "ConfigurationBuilder":
        """Set the base URL by resolving a server configuration with optional variable overrides.

        Calls :meth:`ServerConfiguration.get_url` to resolve the URL template
        with the given variable overrides and stores the result as the base URL.
        If the user also calls :meth:`base_url` after this method, the explicit
        base URL wins (last-write-wins).

        Args:
            server_config: The server configuration to resolve.
            variables: Variable name to value overrides. If ``None``, all
                variables use their default values.

        Returns:
            This builder.

        Raises:
            ValueError: If an override value is not in the variable's
                enum_values.
        """
        self._base_url = server_config.get_url(variables)
        return self

    def default_headers(self, headers: Dict[str, str]) -> "ConfigurationBuilder":
        """Add multiple default headers to include in every API request.

        Args:
            headers: Map of header names to values.

        Returns:
            This builder.
        """
        self._default_headers.update(headers)
        return self

    def build(self) -> Configuration:
        """Build and return an immutable Configuration instance.

        Returns:
            The configured instance.
        """
        return Configuration(
            base_url=self._base_url,
            default_headers=self._default_headers,
        )
