# ruff: noqa
# mypy: ignore-errors
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

import base64
import datetime
import decimal
import json
import re
import uuid
from datetime import timezone
from enum import Enum
from typing import Any, Callable, ClassVar, Optional, Type, TypeVar, Union, cast

from dateutil.parser import parse
from pydantic import BaseModel, SecretStr, TypeAdapter

# The protobuf-JSON duration helpers live in a tiny dependency-free module so
# both this serializer and the generated pydantic models (via the
# ProtobufDuration annotated type) can import them without a circular import
# back through zitadel_client.models.
from zitadel_client._duration import (
    _format_timedelta_protobuf,
    _parse_timedelta_protobuf,
)

# SerializationError inherits from the branded SDK root so callers can catch
# every SDK error (transport + serde) with one `except ZitadelException`.
# The errors module imports ObjectSerializer lazily (inside a method), so this
# top-level import does not create a cycle.
from zitadel_client.errors import ZitadelException

import zitadel_client.models

T = TypeVar("T")

# Module-level TypeAdapter cache for Item 10. TypeAdapter compiles a
# validator + serializer for a generic type once; reusing the instance
# across calls avoids paying that cost on every list/dict deserialization.
_LIST_ADAPTER_CACHE: dict[type, TypeAdapter[Any]] = {}
_DICT_ADAPTER_CACHE: dict[type, TypeAdapter[Any]] = {}


# `inner` is a runtime type object used to build a parametrized container
# type for pydantic. It is annotated as Any (not `type`) because subscripting
# `list[inner]` / `dict[str, inner]` with a `type`-annotated variable is not a
# valid static type expression; Any lets mypy treat the result as the
# (correct) `list[Any]` / `dict[str, Any]` without an inline override.
def _list_adapter(inner: Any) -> TypeAdapter[Any]:
    cached = _LIST_ADAPTER_CACHE.get(inner)
    if cached is None:
        cached = TypeAdapter(list[inner])
        _LIST_ADAPTER_CACHE[inner] = cached
    return cached


def _dict_adapter(inner: Any) -> TypeAdapter[Any]:
    cached = _DICT_ADAPTER_CACHE.get(inner)
    if cached is None:
        cached = TypeAdapter(dict[str, inner])
        _DICT_ADAPTER_CACHE[inner] = cached
    return cached


class SerializationError(ZitadelException):
    """Exception raised when serialization or deserialization fails."""

    def __init__(self, message: str, cause: Optional[Exception] = None):
        super().__init__(message)
        # Stored privately and exposed via read-only @property getters so a
        # caught error's fields cannot be reassigned after construction.
        self._message = message
        self._cause = cause

    @property
    def message(self) -> str:
        return self._message

    @property
    def cause(self) -> Optional[Exception]:
        return self._cause


class ObjectSerializer:
    """Handles JSON serialization and deserialization for API requests and responses.

    All serde operations in the generated client route through this class.
    The parameter encoding methods provide consistent value conversion for
    URL path, query string, header, and form parameters.
    """

    _PRIMITIVE_TYPES = (float, bool, bytes, str, int)

    _NATIVE_TYPES_MAPPING: ClassVar[dict[str, type]] = {
        "int": int,
        "long": int,
        "float": float,
        "str": str,
        "bool": bool,
        "bytes": bytes,
        "date": datetime.date,
        "datetime": datetime.datetime,
        # Item 5 — pydantic AwareDatetime resolves to the stdlib datetime
        # at runtime; pydantic enforces the tz-awareness invariant during
        # model validation, not in this hand-rolled fallback path.
        "AwareDatetime": datetime.datetime,
        "datetime.time": datetime.time,
        "datetime.timedelta": datetime.timedelta,
        "decimal": decimal.Decimal,
        "uuid.UUID": uuid.UUID,
        "object": object,
        # Item 8 — pydantic StrictXxx aliases resolve to their stdlib
        # primitives for the top-level _deserialize() fallback path.
        # Strictness is enforced by per-field StrictXxx annotations on
        # generated models, not by this map.
        "StrictInt": int,
        "StrictFloat": float,
        "StrictBool": bool,
        "StrictStr": str,
    }

    def __init__(self) -> None:
        pass

    def serialize(self, obj: Any) -> str:
        """Serialize an object to a JSON string.

        Uses allow_nan=False so NaN/Infinity/-Infinity raise ValueError
        instead of being emitted as `NaN`/`Infinity` (which RFC 8259
        forbids — Python's default allow_nan=True is non-spec-compliant).
        Aligns Python with the 10 SDKs that already reject non-finite
        floats both on encode and decode.
        """
        try:
            if isinstance(obj, BaseModel):
                if hasattr(obj, "actual_instance"):
                    return self.serialize(obj.actual_instance)
                return obj.model_dump_json(by_alias=True, exclude_none=True)
            return json.dumps(
                ObjectSerializer._sanitize_for_serialization(obj),
                default=str,
                ensure_ascii=False,
                allow_nan=False,
            )
        except Exception as e:
            raise SerializationError(f"Failed to serialize object to JSON: {e}", e)

    @staticmethod
    def _reject_nonfinite_constant(name: str) -> Any:
        # Raised when json.loads encounters NaN/Infinity/-Infinity literals.
        # The default parse_constant accepts them silently; we reject so
        # non-spec-compliant JSON from a misbehaving server fails loudly.
        raise SerializationError(
            f"Non-finite JSON number '{name}' is forbidden by RFC 8259", None
        )

    def deserialize(
        self, json_string: Optional[str], target_type: Union[str, Type[T]]
    ) -> Optional[T]:
        """Deserialize a JSON string to an object of the specified type."""
        try:
            if json_string is None or json_string == "":
                return None

            # RFC 8259 §8.1 forbids a UTF-8 BOM at the start of JSON text,
            # but Windows-generated payloads often include one and Python's
            # json.loads rejects it. Strip silently for parity with Java
            # Jackson / C# System.Text.Json which strip transparently.
            if json_string.startswith("﻿"):
                json_string = json_string[1:]

            data = json.loads(
                json_string,
                parse_constant=ObjectSerializer._reject_nonfinite_constant,
            )
            # _deserialize is dynamically typed (returns Any); narrow it back
            # to the declared Optional[T] for callers without an inline override.
            return cast(Optional[T], self._deserialize(data, target_type))
        except json.JSONDecodeError as e:
            raise SerializationError(f"Failed to parse JSON: {e}", e)
        except Exception as e:
            raise SerializationError(
                f"Failed to deserialize JSON to {target_type}: {e}", e
            )

    @classmethod
    def _sanitize_for_serialization(
        cls, obj: Any, _visited: Optional[set[int]] = None
    ) -> Any:
        """Convert an object to a JSON-safe dict/list/primitive.

        For Pydantic models, delegates to model_dump().
        A visited set tracks object ids to detect circular references.
        """
        if obj is None:
            return None
        elif isinstance(obj, BaseModel):
            return obj.model_dump(by_alias=True, exclude_none=True)
        elif isinstance(obj, Enum):
            return obj.value
        elif isinstance(obj, SecretStr):
            return obj.get_secret_value()
        elif isinstance(obj, bytes):
            return base64.b64encode(obj).decode("ascii")
        elif isinstance(obj, cls._PRIMITIVE_TYPES):
            return obj
        elif isinstance(obj, datetime.datetime):
            dt = obj if obj.tzinfo is not None else obj.replace(tzinfo=timezone.utc)
            return dt.isoformat(timespec="seconds")
        elif isinstance(obj, datetime.timedelta):
            # Must precede the datetime.date branch only because timedelta
            # is not a date subclass; ordered alongside the other temporal
            # types for readability.
            return _format_timedelta_protobuf(obj)
        elif isinstance(obj, datetime.time):
            return obj.isoformat(timespec="seconds")
        elif isinstance(obj, datetime.date):
            return obj.isoformat()
        elif isinstance(obj, decimal.Decimal):
            return str(obj)
        elif isinstance(obj, uuid.UUID):
            return str(obj)
        elif isinstance(obj, (list, tuple, dict)) or hasattr(obj, "__dict__"):
            if _visited is None:
                _visited = set()
            obj_id = id(obj)
            if obj_id in _visited:
                raise SerializationError(
                    "Circular reference detected during serialization"
                )
            _visited.add(obj_id)
            try:
                if isinstance(obj, list):
                    sanitized: Any = [
                        cls._sanitize_for_serialization(item, _visited) for item in obj
                    ]
                elif isinstance(obj, tuple):
                    sanitized = tuple(
                        cls._sanitize_for_serialization(item, _visited) for item in obj
                    )
                elif isinstance(obj, dict):
                    sanitized = {
                        key: cls._sanitize_for_serialization(val, _visited)
                        for key, val in obj.items()
                    }
                else:
                    sanitized = str(obj)
            finally:
                _visited.discard(obj_id)
            return sanitized
        else:
            return str(obj)

    def _resolve_klass_name(self, name: str) -> Optional[type]:
        """Resolve a flat type-name string to a Python type for TypeAdapter.

        Returns ``None`` when the name is a composite (``List[...]`` /
        ``Dict[...]``) so the caller falls back to recursive deserialization.
        Used by the Item 10 TypeAdapter fast path for ``List[T]`` /
        ``Dict[str, T]`` collections.
        """
        if name.startswith("List[") or name.startswith("Dict["):
            return None
        if name in self._NATIVE_TYPES_MAPPING:
            return self._NATIVE_TYPES_MAPPING[name]
        resolved = getattr(zitadel_client.models, name, None)
        if isinstance(resolved, type):
            return resolved
        return None

    def _deserialize(self, data: Any, klass: Any) -> Any:
        """Deserialize parsed data to the target type.

        For Pydantic models, delegates to model_validate().
        """
        if data is None:
            return None

        if isinstance(klass, str):
            if klass.startswith("List["):
                m = re.match(r"List\[(.*)]", klass)
                assert m is not None, "Malformed List type definition"
                sub_kls = m.group(1)
                inner = self._resolve_klass_name(sub_kls)
                # Item 10 — pydantic TypeAdapter handles list-of-model
                # validation natively (one cached adapter per inner type).
                # Falls back to the element-wise recursion only for inner
                # types the adapter can't express (e.g. nested 'List[X]').
                if inner is not None:
                    return _list_adapter(inner).validate_python(data)
                return [self._deserialize(item, sub_kls) for item in data]

            if klass.startswith("Dict["):
                m = re.match(r"Dict\[([^,]*), (.*)]", klass)
                assert m is not None, "Malformed Dict type definition"
                sub_kls = m.group(2)
                inner = self._resolve_klass_name(sub_kls)
                if inner is not None:
                    return _dict_adapter(inner).validate_python(data)
                return {k: self._deserialize(v, sub_kls) for k, v in data.items()}

            if klass in self._NATIVE_TYPES_MAPPING:
                klass = self._NATIVE_TYPES_MAPPING[klass]
            else:
                klass = getattr(zitadel_client.models, klass)

        if isinstance(klass, type) and issubclass(klass, BaseModel):
            if hasattr(klass, "any_of_schemas") or hasattr(klass, "one_of_schemas"):
                return self._deserialize_composed(data, klass)
            return klass.model_validate(data)
        elif klass is bytes:
            if isinstance(data, bytes):
                return data
            if isinstance(data, str):
                return base64.b64decode(data)
            return data
        elif klass in self._PRIMITIVE_TYPES:
            try:
                return klass(data)
            except (UnicodeEncodeError, TypeError):
                return data
        elif klass is object:
            return data
        elif klass == datetime.date:
            return parse(data).date()
        elif klass == datetime.datetime:
            return parse(data)
        elif klass == datetime.time:
            if isinstance(data, datetime.time):
                return data
            return datetime.time.fromisoformat(data)
        elif klass == datetime.timedelta:
            if isinstance(data, datetime.timedelta):
                return data
            return _parse_timedelta_protobuf(data)
        elif klass == decimal.Decimal:
            return decimal.Decimal(data)
        elif klass == uuid.UUID:
            return uuid.UUID(data) if not isinstance(data, uuid.UUID) else data
        elif isinstance(klass, type) and issubclass(klass, Enum):
            return klass(data)
        else:
            return data

    def _deserialize_composed(self, data: Any, klass: type) -> Any:
        """Deserialize data for oneOf/anyOf composed schemas.

        Tries each candidate schema and wraps the first successful
        result in the composed model.

        Gap AU: when the composed schema declares a discriminator, route
        through `get_discriminator_value` so missing / empty / unknown
        discriminator values raise ValueError (matches the other SDKs)
        instead of silently wrapping the raw dict in `actual_instance`.
        """
        schemas: set[str] = (
            getattr(klass, "any_of_schemas", None)
            or getattr(klass, "one_of_schemas", None)
            or set()
        )
        if hasattr(klass, "get_discriminator_value") and isinstance(data, dict):
            mapped = klass.get_discriminator_value(data)
            if mapped:
                instance = self._deserialize(data, mapped)
                return klass(instance)

        for schema_name in schemas:
            try:
                instance = self._deserialize(data, schema_name)
                return klass(instance)
            except Exception:
                continue
        return klass(data)

    @classmethod
    def stringify(cls, value: Any) -> str:
        """Convert a scalar value to its string representation.

        This is the canonical type-conversion method used by all parameter
        encoding helpers and by :class:`ValueSerializer`.

        Args:
            value: The value to convert.

        Returns:
            The string representation of the value.
        """
        if value is None:
            return ""
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, Enum):
            return str(value.value)
        if isinstance(value, datetime.datetime):
            dt = (
                value
                if value.tzinfo is not None
                else value.replace(tzinfo=timezone.utc)
            )
            return dt.isoformat(timespec="seconds")
        if isinstance(value, datetime.timedelta):
            return _format_timedelta_protobuf(value)
        if isinstance(value, datetime.time):
            return value.isoformat(timespec="seconds")
        if isinstance(value, datetime.date):
            return value.isoformat()
        if isinstance(value, uuid.UUID):
            return str(value)
        return str(value)

    @classmethod
    def to_path_value(cls, value: Any) -> str:
        """Convert a value to a string suitable for use as a URL path parameter."""
        return cls.stringify(value)

    @classmethod
    def to_query_value(cls, value: Any, collection_format: Optional[str] = None) -> Any:
        """Convert a value to a representation suitable for use as a query parameter.

        For collections, joins using the specified collection format delimiter.
        """
        if value is None:
            return None
        if isinstance(value, list):
            # Stringify each element; ``None`` becomes an empty slot so that
            # ``[1, None, 3]`` serializes as ``"1,,3"`` (csv keep-slot) for
            # csv/ssv/tsv/pipes joins. For the ``multi`` style, elements are
            # returned as a list and ``None`` is preserved as ``''`` so that
            # the slot is not dropped by downstream encoders.
            items = ["" if v is None else cls.stringify(v) for v in value]
            if collection_format == "multi":
                return items
            if collection_format == "ssv":
                return " ".join(items)
            if collection_format == "tsv":
                return "\t".join(items)
            if collection_format == "pipes":
                return "|".join(items)
            return ",".join(items)
        return cls.stringify(value)

    @classmethod
    def to_header_value(cls, value: Any) -> str:
        """Convert a value to a string suitable for use as an HTTP header value."""
        if value is None:
            return ""
        if isinstance(value, list):
            return ",".join(cls.stringify(v) for v in value)
        return cls.stringify(value)

    @classmethod
    def to_cookie_value(cls, value: Any) -> str:
        """Convert a value to a string suitable for use as an HTTP cookie value.

        Cookie values follow the same encoding rules as header values.
        """
        return cls.to_header_value(value)

    @classmethod
    def to_form_value(cls, value: Any) -> Any:
        """Convert a value to a representation suitable for use as a form parameter."""
        if value is None:
            return ""
        return cls.stringify(value)

    def _resolve_one_of(
        self, json_string: str, candidates: list[Callable[[str], Any]]
    ) -> Any:
        """Resolve a oneOf schema by trying each candidate deserializer in order.

        Args:
            json_string: The JSON string to deserialize.
            candidates: List of callable deserializers that accept a JSON string.

        Returns:
            The first non-None successful result.

        Raises:
            SerializationError: If no candidate matches the JSON. A payload
                satisfying none of the declared variants is a contract violation
                and must fail loudly rather than be silently dropped to None.
        """
        for candidate in candidates:
            try:
                result = candidate(json_string)
                if result is not None:
                    return result
            except Exception:
                continue
        raise SerializationError("No oneOf/anyOf variant matched the JSON")

    def _resolve_any_of(
        self, json_string: str, candidates: list[Callable[[str], Any]]
    ) -> Any:
        """Resolve an anyOf schema by trying each candidate deserializer in order.

        Delegates to _resolve_one_of.

        Args:
            json_string: The JSON string to deserialize.
            candidates: List of callable deserializers that accept a JSON string.

        Returns:
            The first non-None successful result.

        Raises:
            SerializationError: If no candidate matches the JSON.
        """
        return self._resolve_one_of(json_string, candidates)
