name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Install poetry
        run: |
          echo "Installing latest Poetry for Python ${{ matrix.python-version }}"
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Check Installability
        working-directory: project/sanity
        run: |
          poetry add zitadel-client@../library
          poetry run python main.py
