name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Installability
        working-directory: project/sanity
        run: |
          uv venv --python ${{ matrix.python-version }}
          source .venv/bin/activate
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install ../library
          python main.py
