name: Qodana

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      test_artifact_name:
        required: false
        type: string
        default: test-results
      coverage_artifact_name:
        required: false
        type: string
        default: test-coverage
    secrets:
      QODANA_TOKEN:
        required: true

defaults:
  run:
    working-directory: ./

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Download Test Reports Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ inputs.test_artifact_name }}
          path: ./qodana-downloaded-reports/test-results

      - name: Download Coverage Report Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ./.qodana/code-coverage

      - name: Run Qodana
        uses: JetBrains/qodana-action@f5aa2889b113c16bd6aee47817b027537ee33ac7 # v2025.1
        with:
          args: --baseline,.qodana/qodana.sarif.json
          push-fixes: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
