name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  packages: write
  id-token: write
  checks: read

defaults:
  run:
    working-directory: ./

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: To Artifactory

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --group dev --frozen

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 'lts/*'

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-force-install: 'true'
        env:
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
