name: Run Tests

on: push

permissions:
    contents: write

defaults:
    run:
        working-directory: ./

jobs:
    app-testing:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version-file: 'pyproject.toml'
                    cache: 'poetry'

            -   name: Install and configure Poetry
                uses: snok/install-poetry@v1
                with:
                    version: latest
                    virtualenvs-create: true
                    virtualenvs-in-project: true
                    installer-parallel: true

            -   name: Install Dependencies
                run: poetry install

            -   name: Run Junit
                run: poetry run pytest
