name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --no-interaction --sync --all-extras

      - name: Run Tests
        run: poetry run pytest --junitxml=build/reports/junit.xml

      - name: Generate coverage report
        uses: mridang/action-test-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'build/coverage/clover.xml'

      - name: Upload Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: test-results
          path: build/reports/junit.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        with:
          name: Tests
          path: build/reports/junit.xml
          reporter: java-junit
          fail-on-error: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
